/*
 * © 2023. This work is openly licensed via CC0 1.0.
 * https://creativecommons.org/publicdomain/zero/1.0/
 */

package com.fjellsoftware.retaildemo.domain;

import io.loppi.graphql.GraphQLDatabaseQueryConfiguration;
import io.loppi.graphql.GraphQLMutationsConfiguration;
import io.loppi.graphql.GraphQLTypeConfiguration;
import io.loppi.orm.metamodel.Attribute;
import com.fjellsoftware.retaildemo.autogenerated.orm.OrderLineResult;
import com.fjellsoftware.retaildemo.autogenerated.orm.OrderLineMeta;

import java.util.Set;

public class OrderLineDomain {

    public static GraphQLTypeConfiguration<OrderLineResult> createCustomerApiTypeConfiguration(OrderLineMeta orderLineMeta){
        Set<Attribute<OrderLineResult, ?>> outputAttributes = Set.of(orderLineMeta.quantity,
                orderLineMeta.unitPrice, orderLineMeta.product);
        GraphQLDatabaseQueryConfiguration<OrderLineResult> queryConfiguration =
                new GraphQLDatabaseQueryConfiguration<>(outputAttributes)
                        .setIncludePluralRootField(false)
                        .setIncludeOrderBy(Set.of(orderLineMeta.orderLineId));
        GraphQLMutationsConfiguration<OrderLineResult> mutationConfiguration =
                new GraphQLMutationsConfiguration<>(Set.of(orderLineMeta.productId, orderLineMeta.unitPrice, orderLineMeta.quantity))
                .setIncludeInsert(Set.of(orderLineMeta.productId, orderLineMeta.unitPrice, orderLineMeta.quantity), false);
        return new GraphQLTypeConfiguration<>(orderLineMeta.getEntityMetadata())
                .setIncludeQuery(queryConfiguration)
                .setIncludeMutations(mutationConfiguration);
    }

    public static GraphQLTypeConfiguration<OrderLineResult> createStaffApiTypeConfiguration(OrderLineMeta orderLineMeta) {
        GraphQLDatabaseQueryConfiguration<OrderLineResult> queryConfiguration = new GraphQLDatabaseQueryConfiguration<>(
                Set.of(orderLineMeta.orderLineId, orderLineMeta.purchaseOrder, orderLineMeta.product,
                        orderLineMeta.unitPrice, orderLineMeta.quantity))
                .setIncludePluralRootField(false)
                .setIncludeOrderBy(Set.of(orderLineMeta.orderLineId));
        return new GraphQLTypeConfiguration<>(orderLineMeta.getEntityMetadata())
                .setIncludeQuery(queryConfiguration);
    }
}
