/*
 * © 2023. This work is openly licensed via CC0 1.0.
 * https://creativecommons.org/publicdomain/zero/1.0/
 */

package com.fjellsoftware.retaildemo.domain;

import com.fjellsoftware.retaildemo.autogenerated.orm.OrderLineResult;
import com.fjellsoftware.retaildemo.autogenerated.orm.OrderLineMeta;
import io.loppi.graphql.integration.orm.table.GraphQLTableConfiguration;
import io.loppi.graphql.integration.orm.table.mutation.GraphQLInsertMutationConfiguration;
import io.loppi.graphql.integration.orm.table.mutation.GraphQLTableMutationsConfiguration;
import io.loppi.graphql.integration.orm.table.query.GraphQLTablePluralQueryConfiguration;
import io.loppi.graphql.integration.orm.table.query.GraphQLTableQueriesConfiguration;
import io.loppi.orm.metamodel.attribute.Attribute;

import java.util.Set;

public class OrderLineDomain {

    public static GraphQLTableConfiguration<OrderLineResult> createCustomerApiTableConfiguration(OrderLineMeta orderLineMeta){
        Set<Attribute<OrderLineResult, ?>> outputAttributes = Set.of(orderLineMeta.quantity,
                orderLineMeta.unitPrice, orderLineMeta.product);
        GraphQLTablePluralQueryConfiguration<OrderLineResult> pluralQueryConfiguration =
                new GraphQLTablePluralQueryConfiguration<OrderLineResult>()
                .setIncludeOrderBy(Set.of(orderLineMeta.orderLineId));
        GraphQLTableQueriesConfiguration<OrderLineResult> queriesConfiguration =
                new GraphQLTableQueriesConfiguration<>(outputAttributes)
                        .setIncludePluralTableQuery(pluralQueryConfiguration);
        GraphQLInsertMutationConfiguration<OrderLineResult> insertConfiguration =
                new GraphQLInsertMutationConfiguration<>(
                        Set.of(orderLineMeta.productId, orderLineMeta.unitPrice, orderLineMeta.quantity));
        GraphQLTableMutationsConfiguration<OrderLineResult> mutationConfiguration =
                new GraphQLTableMutationsConfiguration<>(
                        Set.of(orderLineMeta.productId, orderLineMeta.unitPrice, orderLineMeta.quantity))
                        .setIncludeInsert(insertConfiguration);
        return new GraphQLTableConfiguration<>(orderLineMeta.getEntityMetadata())
                .setIncludeQueries(queriesConfiguration)
                .setIncludeMutations(mutationConfiguration);
    }

    public static GraphQLTableConfiguration<OrderLineResult> createStaffApiTableConfiguration(
            OrderLineMeta orderLineMeta) {
        GraphQLTableQueriesConfiguration<OrderLineResult> queryConfiguration = new GraphQLTableQueriesConfiguration<>(
                Set.of(orderLineMeta.orderLineId, orderLineMeta.purchaseOrder, orderLineMeta.product,
                        orderLineMeta.unitPrice, orderLineMeta.quantity))
                .setIncludePluralTableQuery(new GraphQLTablePluralQueryConfiguration<OrderLineResult>()
                        .setIncludeOrderBy(Set.of(orderLineMeta.orderLineId)));
        return new GraphQLTableConfiguration<>(orderLineMeta.getEntityMetadata()).setIncludeQueries(queryConfiguration);
    }
}
