package com.fjellsoftware.retaildemo.autogenerated.orm;

import io.loppi.orm.metamodel.RowToDelete;
import org.jetbrains.annotations.NotNull;

/////////////////////
/// AUTOGENERATED ///
/////////////////////

public final class CountryToDelete implements RetailDemoRowToDelete, RowToDelete {
    private final int whereCountryId;

    public CountryToDelete(int whereCountryId){
        this.whereCountryId = whereCountryId;
    }

    public int getWhereCountryId(){
        return whereCountryId;
    }

}