/*
 * © 2023. This work is openly licensed via CC0 1.0.
 * https://creativecommons.org/publicdomain/zero/1.0/
 */

package com.fjellsoftware.retaildemo.autogenerated.orm;

import io.loppi.includablevalues.*;
import io.loppi.orm.metamodel.*;

/////////////////////
/// AUTOGENERATED ///
/////////////////////

public final class CountryMeta{
    private static final Class<CountryResult> referenceClass = CountryResult.class;

    private static final String COUNTRY_ID_FIELD_NAME = "countryId";
    private static final String NAME_FIELD_NAME = "name";
    private static final String PURCHASE_ORDERS_FIELD_NAME = "purchaseOrders";

    static final ScalarAttributeReference<CountryResult, IncludableInt> countryIdInternalReference = 
        new ScalarAttributeReference<>(referenceClass, COUNTRY_ID_FIELD_NAME, IncludableInt.class);
    static final PluralDerivedAssociationAttributeReference<CountryResult, PurchaseOrderResult> purchaseOrdersInternalReference = 
        new PluralDerivedAssociationAttributeReference<>(referenceClass, PURCHASE_ORDERS_FIELD_NAME, PurchaseOrderResult.class);

    public final ScalarAttribute<CountryResult, IncludableInt> countryId;
    public final ScalarAttribute<CountryResult, IncludableString> name;
    public final PluralDerivedAssociationAttribute<CountryResult, PurchaseOrderResult> purchaseOrders;

    private final EntityMetadata<CountryResult> entityMetadata;

    @SuppressWarnings({"unchecked"})
    public CountryMeta(LoppiMetamodel<RetailDemoDatabaseQueryResult> loppiMetamodel){
        this.entityMetadata = loppiMetamodel.getEntityMetadata(referenceClass).getOrThrow();
        this.countryId = (ScalarAttribute<CountryResult, IncludableInt>) entityMetadata.tryGetScalarAttribute(COUNTRY_ID_FIELD_NAME).getOrThrow();
        this.name = (ScalarAttribute<CountryResult, IncludableString>) entityMetadata.tryGetScalarAttribute(NAME_FIELD_NAME).getOrThrow();
        this.purchaseOrders = (PluralDerivedAssociationAttribute<CountryResult, PurchaseOrderResult>) entityMetadata.tryGetAssociationAttribute(PURCHASE_ORDERS_FIELD_NAME).getOrThrow();
    }

    public EntityMetadata<CountryResult> getEntityMetadata(){
        return entityMetadata;
    }
}
