package com.fjellsoftware.retaildemo.autogenerated.orm;

import io.loppi.orm.includablevalues.*;
import io.loppi.orm.metamodel.*;
import com.fjellsoftware.javafunctionalutils.NullUtils;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

import java.beans.ConstructorProperties;

/////////////////////
/// AUTOGENERATED ///
/////////////////////

public final class CountryResult implements RetailDemoTableQueryResult {
    private final IncludableInt countryId;
    private final IncludableString name;
    private final IncludableAssociationList<PurchaseOrderResult> purchaseOrders;

    @ConstructorProperties({"countryId", "name", "purchaseOrders"})
    public CountryResult(
            @NotNull IncludableInt countryId, @NotNull IncludableString name, 
            @NotNull IncludableAssociationList<PurchaseOrderResult> purchaseOrders){
        NullUtils.requireAllNonNull(countryId, name, purchaseOrders);
        this.countryId = countryId;
        this.name = name;
        this.purchaseOrders = purchaseOrders;
    }

    public @NotNull IncludableInt getCountryId(){
        return countryId;
    }

    public @NotNull IncludableString getName(){
        return name;
    }

    public @NotNull IncludableAssociationList<PurchaseOrderResult> getPurchaseOrders(){
        return purchaseOrders;
    }


}