/*
 * © 2023. This work is openly licensed via CC0 1.0.
 * https://creativecommons.org/publicdomain/zero/1.0/
 */

package com.fjellsoftware.retaildemo.autogenerated.orm;

import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.UUID;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

import java.beans.ConstructorProperties;import io.loppi.includablevalues.*;
import io.loppi.orm.LoppiAutogeneratedClassesParser;

/////////////////////
/// AUTOGENERATED ///
/////////////////////

public final class CountryToInsert implements CountryReference, RetailDemoRowToInsert {
    private String name;


    @ConstructorProperties({"name"})
    public CountryToInsert(
            @NotNull String name){
        this.name = name;
    }
    public String getName(){
        return name;
    }

    public void setName(@NotNull String name){
        Objects.requireNonNull(name);
        this.name = name;
    }

    @Override
    public String toString(){
        return LoppiAutogeneratedClassesParser.tryRowToMutateToString(this);
    }

}
