/*
 * © 2023. This work is openly licensed via CC0 1.0.
 * https://creativecommons.org/publicdomain/zero/1.0/
 */

package com.fjellsoftware.retaildemo.autogenerated.orm;

import io.loppi.includablevalues.*;
import io.loppi.orm.LoppiAutogeneratedClassesParser;
import io.loppi.orm.metamodel.*;
import com.fjellsoftware.javafunctionalutils.NullUtils;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

import java.beans.ConstructorProperties;

/////////////////////
/// AUTOGENERATED ///
/////////////////////

public final class CountryResult implements RetailDemoDatabaseQueryResult {
    private final IncludableInt countryId;
    private final IncludableString name;
    private final IncludableAssociationList<PurchaseOrderResult> purchaseOrders;

    @ConstructorProperties({"countryId", "name", "purchaseOrders"})
    public CountryResult(
            IncludableInt countryId, IncludableString name, 
            IncludableAssociationList<PurchaseOrderResult> purchaseOrders){
        NullUtils.requireAllNonNull(countryId, name, purchaseOrders);
        this.countryId = countryId;
        this.name = name;
        this.purchaseOrders = purchaseOrders;
    }

    public IncludableInt getCountryId(){
        return countryId;
    }

    public IncludableString getName(){
        return name;
    }

    public IncludableAssociationList<PurchaseOrderResult> getPurchaseOrders(){
        return purchaseOrders;
    }


}
