package com.fjellsoftware.retaildemo.autogenerated.orm;

import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.UUID;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

import java.beans.ConstructorProperties;
import com.fjellsoftware.javafunctionalutils.NullUtils;
import io.loppi.orm.includablevalues.*;

/////////////////////
/// AUTOGENERATED ///
/////////////////////

public final class CountryToInsert implements CountryReference, RetailDemoRowToInsert {
    private String name;


    @ConstructorProperties({"name"})
    public CountryToInsert(
            @NotNull String name){
        NullUtils.requireAllNonNull(name);
        this.name = name;
    }
    public @NotNull String getName(){
        return name;
    }

    public void setName(@NotNull String name){
        Objects.requireNonNull(name);
        this.name = name;
    }

}