/*
 * © 2023. This work is openly licensed via CC0 1.0.
 * https://creativecommons.org/publicdomain/zero/1.0/
 */

package com.fjellsoftware.retaildemo.autogenerated.orm;

import io.loppi.includablevalues.*;
import io.loppi.orm.LoppiAutogeneratedClassesParser;
import io.loppi.orm.metamodel.*;
import com.fjellsoftware.javafunctionalutils.NullUtils;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

import java.beans.ConstructorProperties;

/////////////////////
/// AUTOGENERATED ///
/////////////////////

public final class LoginSessionResult implements RetailDemoDatabaseQueryResult {
    private final IncludableUUID loginSessionId;
    private final IncludableBoolean isSignedOut;
    private final IncludableOffsetDateTime createdAt;
    private final IncludableOffsetDateTime lastUpdatedAt;
    private final IncludableAssociation<UserAccountResult> userAccount;
    private final IncludableUUID userAccountId;

    @ConstructorProperties({"loginSessionId", "isSignedOut", "createdAt", "lastUpdatedAt", "userAccount", 
        "userAccountId"})
    public LoginSessionResult(
            IncludableUUID loginSessionId, IncludableBoolean isSignedOut, IncludableOffsetDateTime createdAt, 
            IncludableOffsetDateTime lastUpdatedAt, IncludableAssociation<UserAccountResult> userAccount, 
            IncludableUUID userAccountId){
        NullUtils.requireAllNonNull(loginSessionId, isSignedOut, createdAt, lastUpdatedAt, userAccount,
                userAccountId);
        this.loginSessionId = loginSessionId;
        this.isSignedOut = isSignedOut;
        this.createdAt = createdAt;
        this.lastUpdatedAt = lastUpdatedAt;
        this.userAccount = userAccount;
        this.userAccountId = userAccountId;
    }

    public IncludableUUID getLoginSessionId(){
        return loginSessionId;
    }

    public IncludableBoolean getIsSignedOut(){
        return isSignedOut;
    }

    public IncludableOffsetDateTime getCreatedAt(){
        return createdAt;
    }

    public IncludableOffsetDateTime getLastUpdatedAt(){
        return lastUpdatedAt;
    }

    public IncludableAssociation<UserAccountResult> getUserAccount(){
        return userAccount;
    }

    public IncludableUUID getUserAccountId(){
        return userAccountId;
    }


}
