/*
 * © 2023. This work is openly licensed via CC0 1.0.
 * https://creativecommons.org/publicdomain/zero/1.0/
 */

package com.fjellsoftware.retaildemo.autogenerated.orm;

import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.UUID;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

import java.beans.ConstructorProperties;import io.loppi.includablevalues.*;
import io.loppi.orm.LoppiAutogeneratedClassesParser;

/////////////////////
/// AUTOGENERATED ///
/////////////////////

public final class LoginSessionToInsert implements LoginSessionReference, RetailDemoRowToInsert {
    private IncludableUUID loginSessionId = IncludableUUID.notIncluded();
    private IncludableBoolean isSignedOut = IncludableBoolean.notIncluded();
    private IncludableOffsetDateTime createdAt = IncludableOffsetDateTime.notIncluded();
    private IncludableOffsetDateTime lastUpdatedAt = IncludableOffsetDateTime.notIncluded();
    private UserAccountReference userAccount;


    @ConstructorProperties({"userAccount"})
    public LoginSessionToInsert(
            @NotNull UserAccountReference userAccount){
        this.userAccount = userAccount;
    }
    public IncludableUUID getLoginSessionId(){
        return loginSessionId;
    }

    public void setLoginSessionId(@NotNull IncludableUUID loginSessionId){
        Objects.requireNonNull(loginSessionId);
        this.loginSessionId = loginSessionId;
    }

    public void setLoginSessionIdIncludableOf(@NotNull UUID loginSessionId){
        Objects.requireNonNull(loginSessionId);
        this.loginSessionId = IncludableUUID.of(loginSessionId);
    }

    public IncludableBoolean getIsSignedOut(){
        return isSignedOut;
    }

    public void setIsSignedOut(@NotNull IncludableBoolean isSignedOut){
        Objects.requireNonNull(isSignedOut);
        this.isSignedOut = isSignedOut;
    }

    public void setIsSignedOutIncludableOf(boolean isSignedOut){
        this.isSignedOut = IncludableBoolean.of(isSignedOut);
    }

    public IncludableOffsetDateTime getCreatedAt(){
        return createdAt;
    }

    public void setCreatedAt(@NotNull IncludableOffsetDateTime createdAt){
        Objects.requireNonNull(createdAt);
        this.createdAt = createdAt;
    }

    public void setCreatedAtIncludableOf(@NotNull OffsetDateTime createdAt){
        Objects.requireNonNull(createdAt);
        this.createdAt = IncludableOffsetDateTime.of(createdAt);
    }

    public IncludableOffsetDateTime getLastUpdatedAt(){
        return lastUpdatedAt;
    }

    public void setLastUpdatedAt(@NotNull IncludableOffsetDateTime lastUpdatedAt){
        Objects.requireNonNull(lastUpdatedAt);
        this.lastUpdatedAt = lastUpdatedAt;
    }

    public void setLastUpdatedAtIncludableOf(@NotNull OffsetDateTime lastUpdatedAt){
        Objects.requireNonNull(lastUpdatedAt);
        this.lastUpdatedAt = IncludableOffsetDateTime.of(lastUpdatedAt);
    }

    public UserAccountReference getUserAccount(){
        return userAccount;
    }

    public void setUserAccount(@NotNull UserAccountReference userAccount){
        Objects.requireNonNull(userAccount);
        this.userAccount = userAccount;
    }

    @Override
    public String toString(){
        return LoppiAutogeneratedClassesParser.tryRowToMutateToString(this);
    }

}
