/*
 * © 2023. This work is openly licensed via CC0 1.0.
 * https://creativecommons.org/publicdomain/zero/1.0/
 */

package com.fjellsoftware.retaildemo.autogenerated.orm;

import io.loppi.orm.metamodel.*;
import java.util.Arrays;
import java.util.List;

/////////////////////
/// AUTOGENERATED ///
/////////////////////

public final class LoppiMetaConfigurationRetailDemo{
    public List<EntityMetadataConfiguration<? extends DatabaseQueryResult>> createEveryMetadataConfiguration(){
        return Arrays.asList(
            createCountryResultMetadata(),
            createLoginSessionResultMetadata(),
            createMetricKindResultMetadata(),
            createMetricValueResultMetadata(),
            createOrderLineResultMetadata(),
            createProductResultMetadata(),
            createPurchaseOrderResultMetadata(),
            createUserAccountResultMetadata());
    }

    private EntityMetadataConfiguration<CountryResult> createCountryResultMetadata() {
        return new EntityMetadataConfiguration<>(
                "Country", "Countries",
                CountryResult.class, CountryMeta.countryIdInternalReference,
                CountryToInsert.class, CountryToUpdate.class, 
                CountryToDelete.class, CountryReference.class)
                .mapPluralAttributeToSingularAttribute(CountryMeta.purchaseOrdersInternalReference, PurchaseOrderMeta.countryInternalReference);
    }

    private EntityMetadataConfiguration<LoginSessionResult> createLoginSessionResultMetadata() {
        return new EntityMetadataConfiguration<>(
                "LoginSession", "LoginSessions",
                LoginSessionResult.class, LoginSessionMeta.loginSessionIdInternalReference,
                LoginSessionToInsert.class, LoginSessionToUpdate.class, 
                LoginSessionToDelete.class, LoginSessionReference.class);
    }

    private EntityMetadataConfiguration<MetricKindResult> createMetricKindResultMetadata() {
        return new EntityMetadataConfiguration<>(
                "MetricKind", "MetricKinds",
                MetricKindResult.class, MetricKindMeta.metricKindIdInternalReference,
                MetricKindToInsert.class, MetricKindToUpdate.class, 
                MetricKindToDelete.class, MetricKindReference.class)
                .mapPluralAttributeToSingularAttribute(MetricKindMeta.metricValuesInternalReference, MetricValueMeta.metricKindInternalReference);
    }

    private EntityMetadataConfiguration<MetricValueResult> createMetricValueResultMetadata() {
        return new EntityMetadataConfiguration<>(
                "MetricValue", "MetricValues",
                MetricValueResult.class, MetricValueMeta.metricValueIdInternalReference,
                MetricValueToInsert.class, MetricValueToUpdate.class, 
                MetricValueToDelete.class, MetricValueReference.class);
    }

    private EntityMetadataConfiguration<OrderLineResult> createOrderLineResultMetadata() {
        return new EntityMetadataConfiguration<>(
                "OrderLine", "OrderLines",
                OrderLineResult.class, OrderLineMeta.orderLineIdInternalReference,
                OrderLineToInsert.class, OrderLineToUpdate.class, 
                OrderLineToDelete.class, OrderLineReference.class);
    }

    private EntityMetadataConfiguration<ProductResult> createProductResultMetadata() {
        return new EntityMetadataConfiguration<>(
                "Product", "Products",
                ProductResult.class, ProductMeta.productIdInternalReference,
                ProductToInsert.class, ProductToUpdate.class, 
                ProductToDelete.class, ProductReference.class)
                .mapPluralAttributeToSingularAttribute(ProductMeta.orderLinesInternalReference, OrderLineMeta.productInternalReference);
    }

    private EntityMetadataConfiguration<PurchaseOrderResult> createPurchaseOrderResultMetadata() {
        return new EntityMetadataConfiguration<>(
                "PurchaseOrder", "PurchaseOrders",
                PurchaseOrderResult.class, PurchaseOrderMeta.purchaseOrderIdInternalReference,
                PurchaseOrderToInsert.class, PurchaseOrderToUpdate.class, 
                PurchaseOrderToDelete.class, PurchaseOrderReference.class)
                .mapPluralAttributeToSingularAttribute(PurchaseOrderMeta.orderLinesInternalReference, OrderLineMeta.purchaseOrderInternalReference);
    }

    private EntityMetadataConfiguration<UserAccountResult> createUserAccountResultMetadata() {
        return new EntityMetadataConfiguration<>(
                "UserAccount", "UserAccounts",
                UserAccountResult.class, UserAccountMeta.userAccountIdInternalReference,
                UserAccountToInsert.class, UserAccountToUpdate.class, 
                UserAccountToDelete.class, UserAccountReference.class)
                .mapPluralAttributeToSingularAttribute(UserAccountMeta.loginSessionsInternalReference, LoginSessionMeta.userAccountInternalReference)
                .mapPluralAttributeToSingularAttribute(UserAccountMeta.purchaseOrdersInternalReference, PurchaseOrderMeta.customerInternalReference);
    }
}
