/*
 * © 2023. This work is openly licensed via CC0 1.0.
 * https://creativecommons.org/publicdomain/zero/1.0/
 */

package com.fjellsoftware.retaildemo.autogenerated.orm;

import io.loppi.graphql.GraphQLService;
import io.loppi.graphql.GraphQLServiceConfiguration;
import io.loppi.graphql.LoppiGraphQLSchemaConfiguration;
import io.loppi.orm.LoppiService;
import io.loppi.orm.metamodel.IdReferenceConfiguration;
import io.loppi.orm.metamodel.LoppiInitializationException;
import org.jetbrains.annotations.NotNull;

import java.util.Objects;
import javax.sql.DataSource;

/////////////////////
/// AUTOGENERATED ///
/////////////////////

public final class LoppiServiceRetailDemo{
    private final LoppiService<RetailDemoDatabaseQueryResult, RetailDemoRowToMutate> loppiService;
    private final MetaRetailDemo metaRetailDemo;
    private final DatabaseServiceJDBCRetailDemo databaseService;

    public LoppiServiceRetailDemo(DataSource dataSource) throws LoppiInitializationException{
        Objects.requireNonNull(dataSource);
        this.loppiService = LoppiService.initializeJDBC(
                dataSource, new LoppiMetaConfigurationRetailDemo().createEveryMetadataConfiguration(),
                new IdReferenceConfiguration(RetailDemoIdReferenceInt.class, RetailDemoIdReferenceLong.class, RetailDemoIdReferenceUUID.class));
        this.metaRetailDemo = new MetaRetailDemo(loppiService.getLoppiMetamodel(), loppiService.getMainSchema());
        this.databaseService = new DatabaseServiceJDBCRetailDemo(loppiService);
    }

    public @NotNull MetaRetailDemo getMeta(){
        return metaRetailDemo;
    }

    public @NotNull DatabaseServiceJDBCRetailDemo getDatabaseServiceJDBC(){
        return databaseService;
    }

    public @NotNull GraphQLService createGraphQLService(
            LoppiGraphQLSchemaConfiguration loppiGraphQLSchemaConfiguration,
            GraphQLServiceConfiguration graphQLServiceConfiguration){
        return loppiService.createGraphQLService(loppiGraphQLSchemaConfiguration, graphQLServiceConfiguration);
    }
}
