/*
 * © 2023. This work is openly licensed via CC0 1.0.
 * https://creativecommons.org/publicdomain/zero/1.0/
 */

package com.fjellsoftware.retaildemo.autogenerated.orm;

import io.loppi.orm.metamodel.LoppiMetamodel;
import io.loppi.orm.metamodel.LoppiAndSQLMetamodels;
import io.loppi.orm.metamodel.DatabaseSchema;
import org.jetbrains.annotations.NotNull;

/////////////////////
/// AUTOGENERATED ///
/////////////////////

public final class MetaRetailDemo{
    private final LoppiMetamodel<RetailDemoDatabaseQueryResult> loppiMetamodel;
    private final DatabaseSchema databaseSchema;
    private final CountryMeta countryMeta;
    private final LoginSessionMeta loginSessionMeta;
    private final MetricKindMeta metricKindMeta;
    private final MetricValueMeta metricValueMeta;
    private final OrderLineMeta orderLineMeta;
    private final ProductMeta productMeta;
    private final PurchaseOrderMeta purchaseOrderMeta;
    private final UserAccountMeta userAccountMeta;

    MetaRetailDemo(LoppiMetamodel<RetailDemoDatabaseQueryResult> loppiMetamodel, DatabaseSchema databaseSchema){
        this.loppiMetamodel = loppiMetamodel;
        this.databaseSchema = databaseSchema;
        this.countryMeta = new CountryMeta(loppiMetamodel);
        this.loginSessionMeta = new LoginSessionMeta(loppiMetamodel);
        this.metricKindMeta = new MetricKindMeta(loppiMetamodel);
        this.metricValueMeta = new MetricValueMeta(loppiMetamodel);
        this.orderLineMeta = new OrderLineMeta(loppiMetamodel);
        this.productMeta = new ProductMeta(loppiMetamodel);
        this.purchaseOrderMeta = new PurchaseOrderMeta(loppiMetamodel);
        this.userAccountMeta = new UserAccountMeta(loppiMetamodel);
    }

    public @NotNull LoppiMetamodel<RetailDemoDatabaseQueryResult> getLoppiMetamodel(){
        return loppiMetamodel;
    }

    public @NotNull DatabaseSchema getSchema(){
        return databaseSchema;
    }

    public @NotNull CountryMeta getCountryMeta(){
        return countryMeta;
    }

    public @NotNull LoginSessionMeta getLoginSessionMeta(){
        return loginSessionMeta;
    }

    public @NotNull MetricKindMeta getMetricKindMeta(){
        return metricKindMeta;
    }

    public @NotNull MetricValueMeta getMetricValueMeta(){
        return metricValueMeta;
    }

    public @NotNull OrderLineMeta getOrderLineMeta(){
        return orderLineMeta;
    }

    public @NotNull ProductMeta getProductMeta(){
        return productMeta;
    }

    public @NotNull PurchaseOrderMeta getPurchaseOrderMeta(){
        return purchaseOrderMeta;
    }

    public @NotNull UserAccountMeta getUserAccountMeta(){
        return userAccountMeta;
    }

}
