package com.fjellsoftware.retaildemo.autogenerated.orm;

import java.util.UUID;
import java.time.OffsetDateTime;
import java.math.BigDecimal;
import java.util.Objects;

import io.loppi.orm.includablevalues.*;
import io.loppi.orm.metamodel.*;
import org.jetbrains.annotations.NotNull;

/////////////////////
/// AUTOGENERATED ///
/////////////////////

public final class MetricKindToUpdate implements RetailDemoRowToUpdate {
    private final long whereMetricKindId;
    private IncludableString name = IncludableString.notIncluded();
    private IncludableOffsetDateTime createdAt = IncludableOffsetDateTime.notIncluded();

    public MetricKindToUpdate(long whereMetricKindId){
        this.whereMetricKindId = whereMetricKindId;
    }

    public long getWhereMetricKindId(){
        return whereMetricKindId;
    }

    public @NotNull IncludableString getName(){
        return name;
    }

    public void setName(@NotNull IncludableString name){
        Objects.requireNonNull(name);
        this.name = name;
    }

    public void setNameIncludableOf(@NotNull String name){
        Objects.requireNonNull(name);
        this.name = IncludableString.of(name);
    }

    public @NotNull IncludableOffsetDateTime getCreatedAt(){
        return createdAt;
    }

    public void setCreatedAt(@NotNull IncludableOffsetDateTime createdAt){
        Objects.requireNonNull(createdAt);
        this.createdAt = createdAt;
    }

    public void setCreatedAtIncludableOf(@NotNull OffsetDateTime createdAt){
        Objects.requireNonNull(createdAt);
        this.createdAt = IncludableOffsetDateTime.of(createdAt);
    }

}