/*
 * © 2023. This work is openly licensed via CC0 1.0.
 * https://creativecommons.org/publicdomain/zero/1.0/
 */

package com.fjellsoftware.retaildemo.autogenerated.orm;

import io.loppi.orm.metamodel.RowToDelete;
import io.loppi.orm.LoppiAutogeneratedClassesParser;
import org.jetbrains.annotations.NotNull;

/////////////////////
/// AUTOGENERATED ///
/////////////////////

public final class MetricKindToDelete implements RetailDemoRowToDelete, RowToDelete {
    private final long whereMetricKindId;

    public MetricKindToDelete(long whereMetricKindId){
        this.whereMetricKindId = whereMetricKindId;
    }

    public long getWhereMetricKindId(){
        return whereMetricKindId;
    }

    @Override
    public String toString(){
        return LoppiAutogeneratedClassesParser.tryRowToMutateToString(this);
    }

}
