/*
 * © 2023. This work is openly licensed via CC0 1.0.
 * https://creativecommons.org/publicdomain/zero/1.0/
 */

package com.fjellsoftware.retaildemo.autogenerated.orm;

import io.loppi.orm.metamodel.RowToDelete;
import io.loppi.orm.LoppiAutogeneratedClassesParser;
import org.jetbrains.annotations.NotNull;

/////////////////////
/// AUTOGENERATED ///
/////////////////////

public final class MetricValueToDelete implements RetailDemoRowToDelete, RowToDelete {
    private final long whereMetricValueId;

    public MetricValueToDelete(long whereMetricValueId){
        this.whereMetricValueId = whereMetricValueId;
    }

    public long getWhereMetricValueId(){
        return whereMetricValueId;
    }

    @Override
    public String toString(){
        return LoppiAutogeneratedClassesParser.tryRowToMutateToString(this);
    }

}
