/*
 * © 2023. This work is openly licensed via CC0 1.0.
 * https://creativecommons.org/publicdomain/zero/1.0/
 */

package com.fjellsoftware.retaildemo.autogenerated.orm;

import io.loppi.includablevalues.*;
import io.loppi.orm.metamodel.*;

/////////////////////
/// AUTOGENERATED ///
/////////////////////

public final class MetricKindMeta{
    private static final Class<MetricKindResult> referenceClass = MetricKindResult.class;

    private static final String METRIC_KIND_ID_FIELD_NAME = "metricKindId";
    private static final String NAME_FIELD_NAME = "name";
    private static final String CREATED_AT_FIELD_NAME = "createdAt";
    private static final String METRIC_VALUES_FIELD_NAME = "metricValues";

    static final ScalarAttributeReference<MetricKindResult, IncludableLong> metricKindIdInternalReference = 
        new ScalarAttributeReference<>(referenceClass, METRIC_KIND_ID_FIELD_NAME, IncludableLong.class);
    static final PluralDerivedAssociationAttributeReference<MetricKindResult, MetricValueResult> metricValuesInternalReference = 
        new PluralDerivedAssociationAttributeReference<>(referenceClass, METRIC_VALUES_FIELD_NAME, MetricValueResult.class);

    public final ScalarAttribute<MetricKindResult, IncludableLong> metricKindId;
    public final ScalarAttribute<MetricKindResult, IncludableString> name;
    public final ScalarAttribute<MetricKindResult, IncludableOffsetDateTime> createdAt;
    public final PluralDerivedAssociationAttribute<MetricKindResult, MetricValueResult> metricValues;

    private final EntityMetadata<MetricKindResult> entityMetadata;

    @SuppressWarnings({"unchecked"})
    public MetricKindMeta(LoppiMetamodel<RetailDemoDatabaseQueryResult> loppiMetamodel){
        this.entityMetadata = loppiMetamodel.getEntityMetadata(referenceClass).getOrThrow();
        this.metricKindId = (ScalarAttribute<MetricKindResult, IncludableLong>) entityMetadata.tryGetScalarAttribute(METRIC_KIND_ID_FIELD_NAME).getOrThrow();
        this.name = (ScalarAttribute<MetricKindResult, IncludableString>) entityMetadata.tryGetScalarAttribute(NAME_FIELD_NAME).getOrThrow();
        this.createdAt = (ScalarAttribute<MetricKindResult, IncludableOffsetDateTime>) entityMetadata.tryGetScalarAttribute(CREATED_AT_FIELD_NAME).getOrThrow();
        this.metricValues = (PluralDerivedAssociationAttribute<MetricKindResult, MetricValueResult>) entityMetadata.tryGetAssociationAttribute(METRIC_VALUES_FIELD_NAME).getOrThrow();
    }

    public EntityMetadata<MetricKindResult> getEntityMetadata(){
        return entityMetadata;
    }
}
