package com.fjellsoftware.retaildemo.autogenerated.orm;

import io.loppi.orm.metamodel.RowToDelete;
import org.jetbrains.annotations.NotNull;

/////////////////////
/// AUTOGENERATED ///
/////////////////////

public final class MetricKindToDelete implements RetailDemoRowToDelete, RowToDelete {
    private final long whereMetricKindId;

    public MetricKindToDelete(long whereMetricKindId){
        this.whereMetricKindId = whereMetricKindId;
    }

    public long getWhereMetricKindId(){
        return whereMetricKindId;
    }

}