package com.fjellsoftware.retaildemo.autogenerated.orm;

import io.loppi.orm.includablevalues.*;
import io.loppi.orm.metamodel.*;
import io.loppi.orm.metamodel.attribute.*;
import io.loppi.orm.metamodel.attributereference.*;
import com.fjellsoftware.javafunctionalutils.ImmutableMap;

/////////////////////
/// AUTOGENERATED ///
/////////////////////

public final class MetricValueMeta implements MetaWithIdAttribute<MetricValueResult> {
    private static final Class<MetricValueResult> referenceClass = MetricValueResult.class;

    static final String BASE_NAME = "MetricValue";
    static final String PLURAL_NAME = "MetricValues";
    static final String TABLE_NAME = "metric_value";

    private static final String METRIC_VALUE_ID_FIELD_NAME = "metricValueId";
    private static final String METRIC_KIND_FIELD_NAME = "metricKind";
    private static final String METRIC_KIND_ID_FIELD_NAME = "metricKindId";
    private static final String VALUE_FIELD_NAME = "value";
    private static final String CREATED_AT_FIELD_NAME = "createdAt";

    static final ImmutableMap<String,String> COLUMN_ATTRIBUTE_NAME_TO_COLUMN_NAME = ImmutableMap.of(
            new ImmutableMap.Entry<>(METRIC_VALUE_ID_FIELD_NAME, "metric_value_id"),
            new ImmutableMap.Entry<>(METRIC_KIND_FIELD_NAME, "metric_kind_id"),
            new ImmutableMap.Entry<>(METRIC_KIND_ID_FIELD_NAME, "metric_kind_id"),
            new ImmutableMap.Entry<>(VALUE_FIELD_NAME, "value"),
            new ImmutableMap.Entry<>(CREATED_AT_FIELD_NAME, "created_at"));

    static final ScalarAttributeReference<MetricValueResult, IncludableLong> metricValueIdInternalReference = 
        new ScalarAttributeReference<>(referenceClass, METRIC_VALUE_ID_FIELD_NAME, IncludableLong.class);
    static final OwnerAssociationAttributeReference<MetricValueResult, IncludableAssociation<MetricKindResult>, MetricKindResult> metricKindInternalReference = 
        new OwnerAssociationAttributeReference<>(referenceClass, METRIC_KIND_FIELD_NAME, false, MetricKindResult.class);

    public final ScalarAttribute<MetricValueResult, IncludableLong> metricValueId;
    public final OwnerAssociationAttribute<MetricValueResult, IncludableAssociation<MetricKindResult>, MetricKindResult> metricKind;
    public final ScalarAttribute<MetricValueResult, IncludableLong> metricKindId;
    public final ScalarAttribute<MetricValueResult, IncludableDouble> value;
    public final ScalarAttribute<MetricValueResult, IncludableOffsetDateTime> createdAt;

    private final EntityMetadata<MetricValueResult> entity_metadata;

    @SuppressWarnings({"unchecked"})
    public MetricValueMeta(ORMMetamodel<RetailDemoTableQueryResult> oRMMetamodel){
        this.entity_metadata = oRMMetamodel.getEntityMetadata(referenceClass);
        this.metricValueId = (ScalarAttribute<MetricValueResult, IncludableLong>) entity_metadata.getScalarAttributeByName(METRIC_VALUE_ID_FIELD_NAME).getOrThrow();
        this.metricKind = (OwnerAssociationAttribute<MetricValueResult, IncludableAssociation<MetricKindResult>, MetricKindResult>) entity_metadata.getAssociationAttributeByName(METRIC_KIND_FIELD_NAME).getOrThrow();
        this.metricKindId = (ScalarAttribute<MetricValueResult, IncludableLong>) entity_metadata.getScalarAttributeByName(METRIC_KIND_ID_FIELD_NAME).getOrThrow();
        this.value = (ScalarAttribute<MetricValueResult, IncludableDouble>) entity_metadata.getScalarAttributeByName(VALUE_FIELD_NAME).getOrThrow();
        this.createdAt = (ScalarAttribute<MetricValueResult, IncludableOffsetDateTime>) entity_metadata.getScalarAttributeByName(CREATED_AT_FIELD_NAME).getOrThrow();
    }

    public EntityMetadata<MetricValueResult> getEntityMetadata(){
        return entity_metadata;
    }
}