/*
 * © 2023. This work is openly licensed via CC0 1.0.
 * https://creativecommons.org/publicdomain/zero/1.0/
 */

package com.fjellsoftware.retaildemo.autogenerated.orm;

import io.loppi.orm.metamodel.RowToDelete;
import io.loppi.orm.LoppiAutogeneratedClassesParser;
import org.jetbrains.annotations.NotNull;

/////////////////////
/// AUTOGENERATED ///
/////////////////////

public final class OrderLineToDelete implements RetailDemoRowToDelete, RowToDelete {
    private final int whereOrderLineId;

    public OrderLineToDelete(int whereOrderLineId){
        this.whereOrderLineId = whereOrderLineId;
    }

    public int getWhereOrderLineId(){
        return whereOrderLineId;
    }

    @Override
    public String toString(){
        return LoppiAutogeneratedClassesParser.tryRowToMutateToString(this);
    }

}
