/*
 * © 2023. This work is openly licensed via CC0 1.0.
 * https://creativecommons.org/publicdomain/zero/1.0/
 */

package com.fjellsoftware.retaildemo.autogenerated.orm;

import io.loppi.includablevalues.*;
import io.loppi.orm.LoppiAutogeneratedClassesParser;
import io.loppi.orm.metamodel.*;
import com.fjellsoftware.javafunctionalutils.NullUtils;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

import java.beans.ConstructorProperties;

/////////////////////
/// AUTOGENERATED ///
/////////////////////

public final class OrderLineResult implements RetailDemoDatabaseQueryResult {
    private final IncludableAssociation<PurchaseOrderResult> purchaseOrder;
    private final IncludableInt purchaseOrderId;
    private final IncludableInt quantity;
    private final IncludableBigDecimal unitPrice;
    private final IncludableAssociation<ProductResult> product;
    private final IncludableInt productId;
    private final IncludableInt orderLineId;
    private final IncludableOffsetDateTime createdAt;

    @ConstructorProperties({"purchaseOrder", "purchaseOrderId", "quantity", "unitPrice", "product", "productId", 
        "orderLineId", "createdAt"})
    public OrderLineResult(
            IncludableAssociation<PurchaseOrderResult> purchaseOrder, IncludableInt purchaseOrderId, 
            IncludableInt quantity, IncludableBigDecimal unitPrice, IncludableAssociation<ProductResult> product, 
            IncludableInt productId, IncludableInt orderLineId, IncludableOffsetDateTime createdAt){
        NullUtils.requireAllNonNull(purchaseOrder, purchaseOrderId, quantity, unitPrice, product, productId,
                orderLineId, createdAt);
        this.purchaseOrder = purchaseOrder;
        this.purchaseOrderId = purchaseOrderId;
        this.quantity = quantity;
        this.unitPrice = unitPrice;
        this.product = product;
        this.productId = productId;
        this.orderLineId = orderLineId;
        this.createdAt = createdAt;
    }

    public IncludableAssociation<PurchaseOrderResult> getPurchaseOrder(){
        return purchaseOrder;
    }

    public IncludableInt getPurchaseOrderId(){
        return purchaseOrderId;
    }

    public IncludableInt getQuantity(){
        return quantity;
    }

    public IncludableBigDecimal getUnitPrice(){
        return unitPrice;
    }

    public IncludableAssociation<ProductResult> getProduct(){
        return product;
    }

    public IncludableInt getProductId(){
        return productId;
    }

    public IncludableInt getOrderLineId(){
        return orderLineId;
    }

    public IncludableOffsetDateTime getCreatedAt(){
        return createdAt;
    }


}
