/*
 * © 2023. This work is openly licensed via CC0 1.0.
 * https://creativecommons.org/publicdomain/zero/1.0/
 */

package com.fjellsoftware.retaildemo.autogenerated.orm;

import io.loppi.includablevalues.*;
import io.loppi.orm.metamodel.*;

/////////////////////
/// AUTOGENERATED ///
/////////////////////

public final class OrderLineMeta{
    private static final Class<OrderLineResult> referenceClass = OrderLineResult.class;

    private static final String PURCHASE_ORDER_FIELD_NAME = "purchaseOrder";
    private static final String PURCHASE_ORDER_ID_FIELD_NAME = "purchaseOrderId";
    private static final String QUANTITY_FIELD_NAME = "quantity";
    private static final String UNIT_PRICE_FIELD_NAME = "unitPrice";
    private static final String PRODUCT_FIELD_NAME = "product";
    private static final String PRODUCT_ID_FIELD_NAME = "productId";
    private static final String ORDER_LINE_ID_FIELD_NAME = "orderLineId";
    private static final String CREATED_AT_FIELD_NAME = "createdAt";

    static final OwnerAssociationAttributeReference<OrderLineResult, IncludableAssociation<PurchaseOrderResult>, PurchaseOrderResult> purchaseOrderInternalReference = 
        new OwnerAssociationAttributeReference<>(referenceClass, PURCHASE_ORDER_FIELD_NAME, false, PurchaseOrderResult.class);
    static final OwnerAssociationAttributeReference<OrderLineResult, IncludableAssociation<ProductResult>, ProductResult> productInternalReference = 
        new OwnerAssociationAttributeReference<>(referenceClass, PRODUCT_FIELD_NAME, false, ProductResult.class);
    static final ScalarAttributeReference<OrderLineResult, IncludableInt> orderLineIdInternalReference = 
        new ScalarAttributeReference<>(referenceClass, ORDER_LINE_ID_FIELD_NAME, IncludableInt.class);

    public final OwnerAssociationAttribute<OrderLineResult, IncludableAssociation<PurchaseOrderResult>, PurchaseOrderResult> purchaseOrder;
    public final ScalarAttribute<OrderLineResult, IncludableInt> purchaseOrderId;
    public final ScalarAttribute<OrderLineResult, IncludableInt> quantity;
    public final ScalarAttribute<OrderLineResult, IncludableBigDecimal> unitPrice;
    public final OwnerAssociationAttribute<OrderLineResult, IncludableAssociation<ProductResult>, ProductResult> product;
    public final ScalarAttribute<OrderLineResult, IncludableInt> productId;
    public final ScalarAttribute<OrderLineResult, IncludableInt> orderLineId;
    public final ScalarAttribute<OrderLineResult, IncludableOffsetDateTime> createdAt;

    private final EntityMetadata<OrderLineResult> entityMetadata;

    @SuppressWarnings({"unchecked"})
    public OrderLineMeta(LoppiMetamodel<RetailDemoDatabaseQueryResult> loppiMetamodel){
        this.entityMetadata = loppiMetamodel.getEntityMetadata(referenceClass).getOrThrow();
        this.purchaseOrder = (OwnerAssociationAttribute<OrderLineResult, IncludableAssociation<PurchaseOrderResult>, PurchaseOrderResult>) entityMetadata.tryGetAssociationAttribute(PURCHASE_ORDER_FIELD_NAME).getOrThrow();
        this.purchaseOrderId = (ScalarAttribute<OrderLineResult, IncludableInt>) entityMetadata.tryGetScalarAttribute(PURCHASE_ORDER_ID_FIELD_NAME).getOrThrow();
        this.quantity = (ScalarAttribute<OrderLineResult, IncludableInt>) entityMetadata.tryGetScalarAttribute(QUANTITY_FIELD_NAME).getOrThrow();
        this.unitPrice = (ScalarAttribute<OrderLineResult, IncludableBigDecimal>) entityMetadata.tryGetScalarAttribute(UNIT_PRICE_FIELD_NAME).getOrThrow();
        this.product = (OwnerAssociationAttribute<OrderLineResult, IncludableAssociation<ProductResult>, ProductResult>) entityMetadata.tryGetAssociationAttribute(PRODUCT_FIELD_NAME).getOrThrow();
        this.productId = (ScalarAttribute<OrderLineResult, IncludableInt>) entityMetadata.tryGetScalarAttribute(PRODUCT_ID_FIELD_NAME).getOrThrow();
        this.orderLineId = (ScalarAttribute<OrderLineResult, IncludableInt>) entityMetadata.tryGetScalarAttribute(ORDER_LINE_ID_FIELD_NAME).getOrThrow();
        this.createdAt = (ScalarAttribute<OrderLineResult, IncludableOffsetDateTime>) entityMetadata.tryGetScalarAttribute(CREATED_AT_FIELD_NAME).getOrThrow();
    }

    public EntityMetadata<OrderLineResult> getEntityMetadata(){
        return entityMetadata;
    }
}
