package com.fjellsoftware.retaildemo.autogenerated.orm;

import io.loppi.orm.includablevalues.*;
import io.loppi.orm.metamodel.*;
import com.fjellsoftware.javafunctionalutils.NullUtils;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

import java.beans.ConstructorProperties;

/////////////////////
/// AUTOGENERATED ///
/////////////////////

public final class OrderLineResult implements RetailDemoTableQueryResult {
    private final IncludableAssociation<PurchaseOrderResult> purchaseOrder;
    private final IncludableInt purchaseOrderId;
    private final IncludableInt quantity;
    private final IncludableBigDecimal unitPrice;
    private final IncludableAssociation<ProductResult> product;
    private final IncludableInt productId;
    private final IncludableInt orderLineId;
    private final IncludableOffsetDateTime createdAt;

    @ConstructorProperties({"purchaseOrder", "purchaseOrderId", "quantity", "unitPrice", "product", "productId", 
        "orderLineId", "createdAt"})
    public OrderLineResult(
            @NotNull IncludableAssociation<PurchaseOrderResult> purchaseOrder, @NotNull IncludableInt purchaseOrderId, 
            @NotNull IncludableInt quantity, @NotNull IncludableBigDecimal unitPrice, 
            @NotNull IncludableAssociation<ProductResult> product, @NotNull IncludableInt productId, 
            @NotNull IncludableInt orderLineId, @NotNull IncludableOffsetDateTime createdAt){
        NullUtils.requireAllNonNull(purchaseOrder, purchaseOrderId, quantity, unitPrice, product, productId, 
                orderLineId, createdAt);
        this.purchaseOrder = purchaseOrder;
        this.purchaseOrderId = purchaseOrderId;
        this.quantity = quantity;
        this.unitPrice = unitPrice;
        this.product = product;
        this.productId = productId;
        this.orderLineId = orderLineId;
        this.createdAt = createdAt;
    }

    public @NotNull IncludableAssociation<PurchaseOrderResult> getPurchaseOrder(){
        return purchaseOrder;
    }

    public @NotNull IncludableInt getPurchaseOrderId(){
        return purchaseOrderId;
    }

    public @NotNull IncludableInt getQuantity(){
        return quantity;
    }

    public @NotNull IncludableBigDecimal getUnitPrice(){
        return unitPrice;
    }

    public @NotNull IncludableAssociation<ProductResult> getProduct(){
        return product;
    }

    public @NotNull IncludableInt getProductId(){
        return productId;
    }

    public @NotNull IncludableInt getOrderLineId(){
        return orderLineId;
    }

    public @NotNull IncludableOffsetDateTime getCreatedAt(){
        return createdAt;
    }


}