/*
 * © 2023. This work is openly licensed via CC0 1.0.
 * https://creativecommons.org/publicdomain/zero/1.0/
 */

package com.fjellsoftware.retaildemo.autogenerated.orm;

import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.UUID;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

import java.beans.ConstructorProperties;import io.loppi.includablevalues.*;
import io.loppi.orm.LoppiAutogeneratedClassesParser;

/////////////////////
/// AUTOGENERATED ///
/////////////////////

public final class OrderLineToInsert implements OrderLineReference, RetailDemoRowToInsert {
    private PurchaseOrderReference purchaseOrder;
    private int quantity;
    private BigDecimal unitPrice;
    private ProductReference product;
    private IncludableOffsetDateTime createdAt = IncludableOffsetDateTime.notIncluded();


    @ConstructorProperties({"purchaseOrder", "quantity", "unitPrice", "product"})
    public OrderLineToInsert(
            @NotNull PurchaseOrderReference purchaseOrder, @NotNull int quantity, @NotNull BigDecimal unitPrice, 
            @NotNull ProductReference product){
        this.purchaseOrder = purchaseOrder;
        this.quantity = quantity;
        this.unitPrice = unitPrice;
        this.product = product;
    }
    public PurchaseOrderReference getPurchaseOrder(){
        return purchaseOrder;
    }

    public void setPurchaseOrder(@NotNull PurchaseOrderReference purchaseOrder){
        Objects.requireNonNull(purchaseOrder);
        this.purchaseOrder = purchaseOrder;
    }

    public int getQuantity(){
        return quantity;
    }

    public void setQuantity(@NotNull int quantity){
        Objects.requireNonNull(quantity);
        this.quantity = quantity;
    }

    public BigDecimal getUnitPrice(){
        return unitPrice;
    }

    public void setUnitPrice(@NotNull BigDecimal unitPrice){
        Objects.requireNonNull(unitPrice);
        this.unitPrice = unitPrice;
    }

    public ProductReference getProduct(){
        return product;
    }

    public void setProduct(@NotNull ProductReference product){
        Objects.requireNonNull(product);
        this.product = product;
    }

    public IncludableOffsetDateTime getCreatedAt(){
        return createdAt;
    }

    public void setCreatedAt(@NotNull IncludableOffsetDateTime createdAt){
        Objects.requireNonNull(createdAt);
        this.createdAt = createdAt;
    }

    public void setCreatedAtIncludableOf(@NotNull OffsetDateTime createdAt){
        Objects.requireNonNull(createdAt);
        this.createdAt = IncludableOffsetDateTime.of(createdAt);
    }

    @Override
    public String toString(){
        return LoppiAutogeneratedClassesParser.tryRowToMutateToString(this);
    }

}
