/*
 * © 2023. This work is openly licensed via CC0 1.0.
 * https://creativecommons.org/publicdomain/zero/1.0/
 */

package com.fjellsoftware.retaildemo.autogenerated.orm;

import java.util.UUID;
import java.time.OffsetDateTime;
import java.math.BigDecimal;
import java.util.Objects;

import io.loppi.includablevalues.*;
import io.loppi.orm.metamodel.*;
import io.loppi.orm.LoppiAutogeneratedClassesParser;
import org.jetbrains.annotations.NotNull;

/////////////////////
/// AUTOGENERATED ///
/////////////////////

public final class ProductToUpdate implements RetailDemoRowToUpdate {
    private final int whereProductId;
    private IncludableString stockCode = IncludableString.notIncluded();
    private IncludableString description = IncludableString.notIncluded();
    private IncludableBigDecimal currentUnitPrice = IncludableBigDecimal.notIncluded();
    private IncludableOffsetDateTime createdAt = IncludableOffsetDateTime.notIncluded();
    private IncludableOffsetDateTime lastUpdatedAt = IncludableOffsetDateTime.notIncluded();

    public ProductToUpdate(int whereProductId){
        this.whereProductId = whereProductId;
    }

    public int getWhereProductId(){
        return whereProductId;
    }

    public IncludableString getStockCode(){
        return stockCode;
    }

    public void setStockCode(@NotNull IncludableString stockCode){
        Objects.requireNonNull(stockCode);
        this.stockCode = stockCode;
    }

    public void setStockCodeIncludableOf(@NotNull String stockCode){
        Objects.requireNonNull(stockCode);
        this.stockCode = IncludableString.of(stockCode);
    }

    public IncludableString getDescription(){
        return description;
    }

    public void setDescription(@NotNull IncludableString description){
        Objects.requireNonNull(description);
        this.description = description;
    }

    public void setDescriptionIncludableOf(@NotNull String description){
        Objects.requireNonNull(description);
        this.description = IncludableString.of(description);
    }

    public IncludableBigDecimal getCurrentUnitPrice(){
        return currentUnitPrice;
    }

    public void setCurrentUnitPrice(@NotNull IncludableBigDecimal currentUnitPrice){
        Objects.requireNonNull(currentUnitPrice);
        this.currentUnitPrice = currentUnitPrice;
    }

    public void setCurrentUnitPriceIncludableOf(@NotNull BigDecimal currentUnitPrice){
        Objects.requireNonNull(currentUnitPrice);
        this.currentUnitPrice = IncludableBigDecimal.of(currentUnitPrice);
    }

    public IncludableOffsetDateTime getCreatedAt(){
        return createdAt;
    }

    public void setCreatedAt(@NotNull IncludableOffsetDateTime createdAt){
        Objects.requireNonNull(createdAt);
        this.createdAt = createdAt;
    }

    public void setCreatedAtIncludableOf(@NotNull OffsetDateTime createdAt){
        Objects.requireNonNull(createdAt);
        this.createdAt = IncludableOffsetDateTime.of(createdAt);
    }

    public IncludableOffsetDateTime getLastUpdatedAt(){
        return lastUpdatedAt;
    }

    public void setLastUpdatedAt(@NotNull IncludableOffsetDateTime lastUpdatedAt){
        Objects.requireNonNull(lastUpdatedAt);
        this.lastUpdatedAt = lastUpdatedAt;
    }

    public void setLastUpdatedAtIncludableOf(@NotNull OffsetDateTime lastUpdatedAt){
        Objects.requireNonNull(lastUpdatedAt);
        this.lastUpdatedAt = IncludableOffsetDateTime.of(lastUpdatedAt);
    }

    @Override
    public String toString(){
        return LoppiAutogeneratedClassesParser.tryRowToMutateToString(this);
    }

}
