package com.fjellsoftware.retaildemo.autogenerated.orm;

import io.loppi.orm.includablevalues.*;
import io.loppi.orm.metamodel.*;
import com.fjellsoftware.javafunctionalutils.NullUtils;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

import java.beans.ConstructorProperties;

/////////////////////
/// AUTOGENERATED ///
/////////////////////

public final class ProductResult implements RetailDemoTableQueryResult {
    private final IncludableInt productId;
    private final IncludableString stockCode;
    private final IncludableString description;
    private final IncludableBigDecimal currentUnitPrice;
    private final IncludableOffsetDateTime createdAt;
    private final IncludableOffsetDateTime lastUpdatedAt;
    private final IncludableAssociationList<OrderLineResult> orderLines;

    @ConstructorProperties({"productId", "stockCode", "description", "currentUnitPrice", "createdAt", "lastUpdatedAt", 
        "orderLines"})
    public ProductResult(
            @NotNull IncludableInt productId, @NotNull IncludableString stockCode, 
            @NotNull IncludableString description, @NotNull IncludableBigDecimal currentUnitPrice, 
            @NotNull IncludableOffsetDateTime createdAt, @NotNull IncludableOffsetDateTime lastUpdatedAt, 
            @NotNull IncludableAssociationList<OrderLineResult> orderLines){
        NullUtils.requireAllNonNull(productId, stockCode, description, currentUnitPrice, createdAt, lastUpdatedAt, 
                orderLines);
        this.productId = productId;
        this.stockCode = stockCode;
        this.description = description;
        this.currentUnitPrice = currentUnitPrice;
        this.createdAt = createdAt;
        this.lastUpdatedAt = lastUpdatedAt;
        this.orderLines = orderLines;
    }

    public @NotNull IncludableInt getProductId(){
        return productId;
    }

    public @NotNull IncludableString getStockCode(){
        return stockCode;
    }

    public @NotNull IncludableString getDescription(){
        return description;
    }

    public @NotNull IncludableBigDecimal getCurrentUnitPrice(){
        return currentUnitPrice;
    }

    public @NotNull IncludableOffsetDateTime getCreatedAt(){
        return createdAt;
    }

    public @NotNull IncludableOffsetDateTime getLastUpdatedAt(){
        return lastUpdatedAt;
    }

    public @NotNull IncludableAssociationList<OrderLineResult> getOrderLines(){
        return orderLines;
    }


}