package com.fjellsoftware.retaildemo.autogenerated.orm;

import io.loppi.orm.metamodel.RowToDelete;
import org.jetbrains.annotations.NotNull;

/////////////////////
/// AUTOGENERATED ///
/////////////////////

public final class ProductToDelete implements RetailDemoRowToDelete, RowToDelete {
    private final int whereProductId;

    public ProductToDelete(int whereProductId){
        this.whereProductId = whereProductId;
    }

    public int getWhereProductId(){
        return whereProductId;
    }

}