package com.fjellsoftware.retaildemo.autogenerated.orm;

import java.util.UUID;

/////////////////////
/// AUTOGENERATED ///
/////////////////////

public sealed interface PurchaseOrderReference extends RetailDemoRowReference permits PurchaseOrderToInsert, RetailDemoIdReferenceInt {
    static PurchaseOrderReference of(int purchaseOrderId){
        return new RetailDemoIdReferenceInt(purchaseOrderId);
    }
}
