/*
 * © 2023. This work is openly licensed via CC0 1.0.
 * https://creativecommons.org/publicdomain/zero/1.0/
 */

package com.fjellsoftware.retaildemo.autogenerated.orm;

import io.loppi.includablevalues.*;
import io.loppi.orm.metamodel.*;

/////////////////////
/// AUTOGENERATED ///
/////////////////////

public final class PurchaseOrderMeta{
    private static final Class<PurchaseOrderResult> referenceClass = PurchaseOrderResult.class;

    private static final String PURCHASE_ORDER_ID_FIELD_NAME = "purchaseOrderId";
    private static final String COUNTRY_FIELD_NAME = "country";
    private static final String COUNTRY_ID_FIELD_NAME = "countryId";
    private static final String CREATED_AT_FIELD_NAME = "createdAt";
    private static final String LAST_UPDATED_AT_FIELD_NAME = "lastUpdatedAt";
    private static final String ORDER_STATUS_FIELD_NAME = "orderStatus";
    private static final String ADDRESS_FIELD_NAME = "address";
    private static final String NAME_FIELD_NAME = "name";
    private static final String PHONE_NUMBER_FIELD_NAME = "phoneNumber";
    private static final String CUSTOMER_FIELD_NAME = "customer";
    private static final String CUSTOMER_ID_FIELD_NAME = "customerId";
    private static final String ORDER_LINES_FIELD_NAME = "orderLines";

    static final ScalarAttributeReference<PurchaseOrderResult, IncludableInt> purchaseOrderIdInternalReference = 
        new ScalarAttributeReference<>(referenceClass, PURCHASE_ORDER_ID_FIELD_NAME, IncludableInt.class);
    static final OwnerAssociationAttributeReference<PurchaseOrderResult, IncludableAssociation<CountryResult>, CountryResult> countryInternalReference = 
        new OwnerAssociationAttributeReference<>(referenceClass, COUNTRY_FIELD_NAME, false, CountryResult.class);
    static final OwnerAssociationAttributeReference<PurchaseOrderResult, IncludableNullableAssociation<UserAccountResult>, UserAccountResult> customerInternalReference = 
        new OwnerAssociationAttributeReference<>(referenceClass, CUSTOMER_FIELD_NAME, true, UserAccountResult.class);
    static final PluralDerivedAssociationAttributeReference<PurchaseOrderResult, OrderLineResult> orderLinesInternalReference = 
        new PluralDerivedAssociationAttributeReference<>(referenceClass, ORDER_LINES_FIELD_NAME, OrderLineResult.class);

    public final ScalarAttribute<PurchaseOrderResult, IncludableInt> purchaseOrderId;
    public final OwnerAssociationAttribute<PurchaseOrderResult, IncludableAssociation<CountryResult>, CountryResult> country;
    public final ScalarAttribute<PurchaseOrderResult, IncludableInt> countryId;
    public final ScalarAttribute<PurchaseOrderResult, IncludableOffsetDateTime> createdAt;
    public final ScalarAttribute<PurchaseOrderResult, IncludableOffsetDateTime> lastUpdatedAt;
    public final ScalarAttribute<PurchaseOrderResult, IncludableString> orderStatus;
    public final ScalarAttribute<PurchaseOrderResult, IncludableString> address;
    public final ScalarAttribute<PurchaseOrderResult, IncludableString> name;
    public final ScalarAttribute<PurchaseOrderResult, IncludableString> phoneNumber;
    public final OwnerAssociationAttribute<PurchaseOrderResult, IncludableNullableAssociation<UserAccountResult>, UserAccountResult> customer;
    public final ScalarAttribute<PurchaseOrderResult, IncludableNullableUUID> customerId;
    public final PluralDerivedAssociationAttribute<PurchaseOrderResult, OrderLineResult> orderLines;

    private final EntityMetadata<PurchaseOrderResult> entityMetadata;

    @SuppressWarnings({"unchecked"})
    public PurchaseOrderMeta(LoppiMetamodel<RetailDemoDatabaseQueryResult> loppiMetamodel){
        this.entityMetadata = loppiMetamodel.getEntityMetadata(referenceClass).getOrThrow();
        this.purchaseOrderId = (ScalarAttribute<PurchaseOrderResult, IncludableInt>) entityMetadata.tryGetScalarAttribute(PURCHASE_ORDER_ID_FIELD_NAME).getOrThrow();
        this.country = (OwnerAssociationAttribute<PurchaseOrderResult, IncludableAssociation<CountryResult>, CountryResult>) entityMetadata.tryGetAssociationAttribute(COUNTRY_FIELD_NAME).getOrThrow();
        this.countryId = (ScalarAttribute<PurchaseOrderResult, IncludableInt>) entityMetadata.tryGetScalarAttribute(COUNTRY_ID_FIELD_NAME).getOrThrow();
        this.createdAt = (ScalarAttribute<PurchaseOrderResult, IncludableOffsetDateTime>) entityMetadata.tryGetScalarAttribute(CREATED_AT_FIELD_NAME).getOrThrow();
        this.lastUpdatedAt = (ScalarAttribute<PurchaseOrderResult, IncludableOffsetDateTime>) entityMetadata.tryGetScalarAttribute(LAST_UPDATED_AT_FIELD_NAME).getOrThrow();
        this.orderStatus = (ScalarAttribute<PurchaseOrderResult, IncludableString>) entityMetadata.tryGetScalarAttribute(ORDER_STATUS_FIELD_NAME).getOrThrow();
        this.address = (ScalarAttribute<PurchaseOrderResult, IncludableString>) entityMetadata.tryGetScalarAttribute(ADDRESS_FIELD_NAME).getOrThrow();
        this.name = (ScalarAttribute<PurchaseOrderResult, IncludableString>) entityMetadata.tryGetScalarAttribute(NAME_FIELD_NAME).getOrThrow();
        this.phoneNumber = (ScalarAttribute<PurchaseOrderResult, IncludableString>) entityMetadata.tryGetScalarAttribute(PHONE_NUMBER_FIELD_NAME).getOrThrow();
        this.customer = (OwnerAssociationAttribute<PurchaseOrderResult, IncludableNullableAssociation<UserAccountResult>, UserAccountResult>) entityMetadata.tryGetAssociationAttribute(CUSTOMER_FIELD_NAME).getOrThrow();
        this.customerId = (ScalarAttribute<PurchaseOrderResult, IncludableNullableUUID>) entityMetadata.tryGetScalarAttribute(CUSTOMER_ID_FIELD_NAME).getOrThrow();
        this.orderLines = (PluralDerivedAssociationAttribute<PurchaseOrderResult, OrderLineResult>) entityMetadata.tryGetAssociationAttribute(ORDER_LINES_FIELD_NAME).getOrThrow();
    }

    public EntityMetadata<PurchaseOrderResult> getEntityMetadata(){
        return entityMetadata;
    }
}
