package com.fjellsoftware.retaildemo.autogenerated.orm;

import java.util.UUID;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

/////////////////////
/// AUTOGENERATED ///
/////////////////////

public final class RetailDemoIdReferenceUUID implements
LoginSessionReference, UserAccountReference 
    {

    private final UUID id;

    public RetailDemoIdReferenceUUID(@NotNull UUID id) {
        Objects.requireNonNull(id);
        this.id = id;
    }

    public UUID getId() {
        return id;
    }

    @Override
    public String toString(){
        return "IdReferenceUUID: { id: " + id + "}";
    }

    @Override
    public int hashCode(){
        long x = id.getMostSignificantBits();
        long y = id.getLeastSignificantBits();
        int result = (int) (x ^ (x >>> 32));
        result = 31 * result + (int) (y ^ (y >>> 32));
        return result;
    }

    @Override
    public boolean equals(Object obj){
        if(obj == this){
            return true;
        }
        if(!(obj instanceof RetailDemoIdReferenceUUID)){
            return false;
        }
        return ((RetailDemoIdReferenceUUID) obj).id.equals(id);
    }


}