package com.fjellsoftware.retaildemo.autogenerated.orm;


import io.loppi.orm.*;
import io.loppi.orm.metamodel.EntityMetadata;
import io.loppi.orm.query.*;
import io.loppi.orm.query.tablequerybuilder.TableQueryBuilder;
import org.jetbrains.annotations.NotNull;

import java.util.List;
import java.util.Set;

/////////////////////
/// AUTOGENERATED ///
/////////////////////

public class RetailDemoDatabaseService {

    private final ORMService<RetailDemoTableQueryResult, RetailDemoRowToMutate> ormServiceInternal;

    RetailDemoDatabaseService(
            ORMService<RetailDemoTableQueryResult, RetailDemoRowToMutate> ormServiceInternal) {
        this.ormServiceInternal = ormServiceInternal;
    }

    public <T extends RetailDemoTableQueryResult> @NotNull QueryExecutionPluralResult<T> executeTableQuery(@NotNull TableQuery<T> tableQuery)
            throws PostgresExecutionException {
        return this.ormServiceInternal.executeTableQuery(tableQuery);
    }

    public @NotNull MutationExecutionResult executeMutation(
            @NotNull List<? extends RetailDemoRowToMutate> mutation) 
            throws PostgresExecutionException, DuplicateIdModificationException {
        return ormServiceInternal.executeMutation(mutation);
    }

    public <T extends RetailDemoTableQueryResult> @NotNull MutationQueryExecutionResult<T> executeMutationQuery(
            @NotNull List<? extends RetailDemoRowToMutate> mutation, @NotNull TableQuery<T> tableQuery)
            throws PostgresExecutionException, DuplicateIdModificationException {
        return ormServiceInternal.executeMutationQuery(mutation, tableQuery);
    }

    public <T extends RetailDemoTableQueryResult> @NotNull TableQueryBuilder<T> createTableQueryBuilder(
            @NotNull EntityMetadata<T> entityMetadata, int limit){
        return ormServiceInternal.createTableQueryBuilder(entityMetadata, limit);
    }
}
