/*
 * © 2023. This work is openly licensed via CC0 1.0.
 * https://creativecommons.org/publicdomain/zero/1.0/
 */

package com.fjellsoftware.retaildemo.autogenerated.orm;

import io.loppi.orm.metamodel.RowToUpsert;

/////////////////////
/// AUTOGENERATED ///
/////////////////////

public sealed interface RetailDemoRowToUpsert extends RowToUpsert, RetailDemoRowToMutate permits 
        RetailDemoRowToInsert, RetailDemoRowToUpdate {}
