/*
 * © 2023. This work is openly licensed via CC0 1.0.
 * https://creativecommons.org/publicdomain/zero/1.0/
 */

package com.fjellsoftware.retaildemo.autogenerated.orm;

import io.loppi.orm.metamodel.RowReference;

/////////////////////
/// AUTOGENERATED ///
/////////////////////

public sealed interface RetailDemoRowReference extends RowReference permits 
CountryReference, LoginSessionReference, MetricKindReference, MetricValueReference, OrderLineReference, 
ProductReference, PurchaseOrderReference, UserAccountReference {
}
