/*
 * © 2023. This work is openly licensed via CC0 1.0.
 * https://creativecommons.org/publicdomain/zero/1.0/
 */

package com.fjellsoftware.retaildemo.autogenerated.orm;

import java.util.UUID;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

/////////////////////
/// AUTOGENERATED ///
/////////////////////

public final class RetailDemoIdReferenceLong implements
MetricKindReference, MetricValueReference 
    {

    private final long id;

    public RetailDemoIdReferenceLong(long id) {
        this.id = id;
    }

    public long getId() {
        return id;
    }

    @Override
    public String toString(){
        return "IdReferenceLong: { id: " + id + "}";
    }

    @Override
    public int hashCode(){
        return Long.hashCode(id);
    }

    @Override
    public boolean equals(Object obj){
        if(obj == this){
            return true;
        }
        if(!(obj instanceof RetailDemoIdReferenceLong)){
            return false;
        }
        return ((RetailDemoIdReferenceLong) obj).id == id;
    }


}
