package com.fjellsoftware.retaildemo.autogenerated.orm;

import io.loppi.orm.metamodel.RowToMutate;

/////////////////////
/// AUTOGENERATED ///
/////////////////////

public sealed interface RetailDemoRowToMutate extends RowToMutate permits 
        RetailDemoRowToUpsert, RetailDemoRowToDelete {
}