/*
 * © 2023. This work is openly licensed via CC0 1.0.
 * https://creativecommons.org/publicdomain/zero/1.0/
 */

package com.fjellsoftware.retaildemo.autogenerated.orm;

import io.loppi.orm.metamodel.RowToDelete;

/////////////////////
/// AUTOGENERATED ///
/////////////////////

public sealed interface RetailDemoRowToDelete extends RowToDelete, RetailDemoRowToMutate permits 
CountryToDelete, LoginSessionToDelete, MetricKindToDelete, MetricValueToDelete, OrderLineToDelete, 
ProductToDelete, PurchaseOrderToDelete, UserAccountToDelete {}
