package com.fjellsoftware.retaildemo.autogenerated.orm;

import io.loppi.orm.metamodel.TableQueryResult;

/////////////////////
/// AUTOGENERATED ///
/////////////////////

public sealed interface RetailDemoTableQueryResult extends TableQueryResult permits 
CountryResult, LoginSessionResult, MetricKindResult, MetricValueResult, OrderLineResult, 
ProductResult, PurchaseOrderResult, UserAccountResult {
}