/*
 * © 2023. This work is openly licensed via CC0 1.0.
 * https://creativecommons.org/publicdomain/zero/1.0/
 */

package com.fjellsoftware.retaildemo.autogenerated.orm;

import io.loppi.orm.metamodel.RowToInsert;

/////////////////////
/// AUTOGENERATED ///
/////////////////////

public sealed interface RetailDemoRowToInsert extends RowToInsert, RetailDemoRowToUpsert permits 
CountryToInsert, LoginSessionToInsert, MetricKindToInsert, MetricValueToInsert, OrderLineToInsert, 
ProductToInsert, PurchaseOrderToInsert, UserAccountToInsert {}
