package com.fjellsoftware.retaildemo.autogenerated.orm;

import io.loppi.orm.metamodel.RowToUpsert;

/////////////////////
/// AUTOGENERATED ///
/////////////////////

public sealed interface RetailDemoRowToUpsert extends RowToUpsert, RetailDemoRowToMutate permits 
        RetailDemoRowToInsert, RetailDemoRowToUpdate {}