/*
 * © 2023. This work is openly licensed via CC0 1.0.
 * https://creativecommons.org/publicdomain/zero/1.0/
 */

package com.fjellsoftware.retaildemo.autogenerated.orm;

import io.loppi.orm.metamodel.RowToUpdate;

/////////////////////
/// AUTOGENERATED ///
/////////////////////

public sealed interface RetailDemoRowToUpdate extends RowToUpdate, RetailDemoRowToUpsert permits 
CountryToUpdate, LoginSessionToUpdate, MetricKindToUpdate, MetricValueToUpdate, OrderLineToUpdate, 
ProductToUpdate, PurchaseOrderToUpdate, UserAccountToUpdate {}
