package com.fjellsoftware.retaildemo.autogenerated.orm;

import io.loppi.orm.metamodel.RowToInsert;

/////////////////////
/// AUTOGENERATED ///
/////////////////////

public sealed interface RetailDemoRowToInsert extends RowToInsert, RetailDemoRowToUpsert permits 
CountryToInsert, LoginSessionToInsert, MetricKindToInsert, MetricValueToInsert, OrderLineToInsert, 
ProductToInsert, PurchaseOrderToInsert, UserAccountToInsert {}