/*
 * © 2023. This work is openly licensed via CC0 1.0.
 * https://creativecommons.org/publicdomain/zero/1.0/
 */

package com.fjellsoftware.retaildemo.autogenerated.orm;

import io.loppi.includablevalues.*;
import io.loppi.orm.LoppiAutogeneratedClassesParser;
import io.loppi.orm.metamodel.*;
import com.fjellsoftware.javafunctionalutils.NullUtils;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

import java.beans.ConstructorProperties;

/////////////////////
/// AUTOGENERATED ///
/////////////////////

public final class UserAccountResult implements RetailDemoDatabaseQueryResult {
    private final IncludableString name;
    private final IncludableString username;
    private final IncludableString hashedPassword;
    private final IncludableOffsetDateTime createdAt;
    private final IncludableOffsetDateTime lastUpdatedAt;
    private final IncludableString role;
    private final IncludableUUID userAccountId;
    private final IncludableAssociationList<LoginSessionResult> loginSessions;
    private final IncludableAssociationList<PurchaseOrderResult> purchaseOrders;

    @ConstructorProperties({"name", "username", "hashedPassword", "createdAt", "lastUpdatedAt", "role", 
        "userAccountId", "loginSessions", "purchaseOrders"})
    public UserAccountResult(
            IncludableString name, IncludableString username, IncludableString hashedPassword, 
            IncludableOffsetDateTime createdAt, IncludableOffsetDateTime lastUpdatedAt, IncludableString role, 
            IncludableUUID userAccountId, IncludableAssociationList<LoginSessionResult> loginSessions, 
            IncludableAssociationList<PurchaseOrderResult> purchaseOrders){
        NullUtils.requireAllNonNull(name, username, hashedPassword, createdAt, lastUpdatedAt, role, userAccountId,
                loginSessions, purchaseOrders);
        this.name = name;
        this.username = username;
        this.hashedPassword = hashedPassword;
        this.createdAt = createdAt;
        this.lastUpdatedAt = lastUpdatedAt;
        this.role = role;
        this.userAccountId = userAccountId;
        this.loginSessions = loginSessions;
        this.purchaseOrders = purchaseOrders;
    }

    public IncludableString getName(){
        return name;
    }

    public IncludableString getUsername(){
        return username;
    }

    public IncludableString getHashedPassword(){
        return hashedPassword;
    }

    public IncludableOffsetDateTime getCreatedAt(){
        return createdAt;
    }

    public IncludableOffsetDateTime getLastUpdatedAt(){
        return lastUpdatedAt;
    }

    public IncludableString getRole(){
        return role;
    }

    public IncludableUUID getUserAccountId(){
        return userAccountId;
    }

    public IncludableAssociationList<LoginSessionResult> getLoginSessions(){
        return loginSessions;
    }

    public IncludableAssociationList<PurchaseOrderResult> getPurchaseOrders(){
        return purchaseOrders;
    }


}
