package com.fjellsoftware.retaildemo.autogenerated.orm;

import io.loppi.orm.metamodel.RowToDelete;
import java.util.UUID;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

/////////////////////
/// AUTOGENERATED ///
/////////////////////

public final class UserAccountToDelete implements RetailDemoRowToDelete, RowToDelete {
    private final UUID whereUserAccountId;

    public UserAccountToDelete(@NotNull UUID whereUserAccountId){
        Objects.requireNonNull(whereUserAccountId);
        this.whereUserAccountId = whereUserAccountId;
    }

    public @NotNull UUID getWhereUserAccountId(){
        return whereUserAccountId;
    }

}