package com.fjellsoftware.retaildemo.autogenerated.graphql.customer;

import com.fjellsoftware.javafunctionalutils.opt.Opt;


/////////////////////
/// AUTOGENERATED ///
/////////////////////


public sealed interface CustomerRequest permits CustomerQueryRequest, CustomerMutationRequest {
    Opt<String> operationName();
}