package com.fjellsoftware.retaildemo.autogenerated.graphql.customer;

/////////////////////
/// AUTOGENERATED ///
/////////////////////

public sealed interface CustomerMutationRootField permits CustomerTableMutationRootField, CustomerOrdinaryMutationRootField {}