/*
 * © 2023. This work is openly licensed via CC0 1.0.
 * https://creativecommons.org/publicdomain/zero/1.0/
 */

package com.fjellsoftware.retaildemo.autogenerated.graphql.customer;

import com.fjellsoftware.javafunctionalutils.opt.Opt;
import io.loppi.graphql.GraphQLIntrospectionQueryField;

/////////////////////
/// AUTOGENERATED ///
/////////////////////

public record CustomerIntrospectionRootField(GraphQLIntrospectionQueryField queryField) implements CustomerQueryRootField{}
