package com.fjellsoftware.retaildemo.autogenerated.graphql.customer;

import com.fjellsoftware.javafunctionalutils.ImmutableList;


import com.fjellsoftware.javafunctionalutils.opt.Opt;

/////////////////////
/// AUTOGENERATED ///
/////////////////////

public record CustomerQueryRequest(Opt<String> operationName, ImmutableList<CustomerQueryRootField> rootFields) implements CustomerRequest {}