package com.fjellsoftware.retaildemo.autogenerated.graphql.customer;
import io.loppi.graphql.*;
import com.fjellsoftware.retaildemo.autogenerated.orm.main.RetailDemoRowToMutate;
import io.loppi.graphql.integration.orm.GraphQLResolvedWithRowsMutationField;
import org.jetbrains.annotations.NotNull;
import com.fjellsoftware.javafunctionalutils.NullUtils;
import java.util.List;

/////////////////////
/// AUTOGENERATED ///
/////////////////////

public class CustomerGraphQLService {
    private final GraphQLServiceForGeneratedClassesInternal<CustomerRequest> graphQLServiceWithDatabaseInternal;
    private final GraphQLService graphQLService;

    public CustomerGraphQLService(@NotNull GraphQLService graphQLService){
        NullUtils.requireAllNonNull(graphQLService);
        this.graphQLServiceWithDatabaseInternal = new GraphQLServiceForGeneratedClassesInternal<>(graphQLService, CustomerRequest.class);
        this.graphQLService = graphQLService;
    }

    public @NotNull CustomerRequest parseAndValidate(@NotNull String body) throws GraphQLRequestException {
        NullUtils.requireAllNonNull(body);
        return graphQLServiceWithDatabaseInternal.parseAndValidate(body);
    }

    public @NotNull GraphQLExecutionResult executeQuery(@NotNull List<GraphQLExecutableQueryField> graphQLQueryDocument){
        NullUtils.requireAllNonNullIterable(graphQLQueryDocument);
        return graphQLService.executeQuery(graphQLQueryDocument);
    }

    public @NotNull GraphQLExecutionResult executeMutation(@NotNull List<GraphQLExecutableMutationField> mutationFields){
        NullUtils.requireAllNonNullIterable(mutationFields);
        return graphQLService.executeMutation(mutationFields);
    }

        public <R> @NotNull GraphQLResolvedMutationField resolveMutationField(
            @NotNull R successfulResult, @NotNull CustomerOrdinaryMutationRootField<R> sourceField){
        return graphQLServiceWithDatabaseInternal.resolveMutationField(successfulResult, sourceField);
    }
    
    public <R> @NotNull GraphQLResolvedWithRowsMutationField resolveWithRowsMutationField(
            @NotNull R successfulResult, @NotNull CustomerOrdinaryMutationRootField<R> sourceField, @NotNull Iterable<? extends RetailDemoRowToMutate> allRowsToMutate){
        return graphQLServiceWithDatabaseInternal.resolveWithRowsMutationField(successfulResult, sourceField, allRowsToMutate);
    }


}