package com.fjellsoftware.retaildemo.autogenerated.graphql.customer;

import io.loppi.graphql.GraphQLQueryField;


/////////////////////
/// AUTOGENERATED ///
/////////////////////


public sealed interface CustomerQueryRootField permits CustomerTableQueryRootField, CustomerIntrospectionRootField {}
