/*
 * © 2023. This work is openly licensed via CC0 1.0.
 * https://creativecommons.org/publicdomain/zero/1.0/
 */

package com.fjellsoftware.retaildemo.autogenerated.graphql.customer;

import io.loppi.graphql.GraphQLCustomMutationField;
import io.loppi.graphql.GraphQLInputTypeForReflection;
import io.loppi.graphql.GraphQLOutputTypeForReflection;


/////////////////////
/// AUTOGENERATED ///
/////////////////////

public sealed interface CustomerCustomMutationRootField<T extends GraphQLOutputTypeForReflection>
        extends CustomerMutationRootField, GraphQLCustomMutationField<T> permits 
        UpdatePasswordMutationField, DemoUpgradeToStaffMutationField, SignOutMutationField, LoginMutationField, SignUpMutationField, DemoDowngradeToCustomerMutationField, VerifyCaptchaMutationField, GetBcryptSaltMutationField {}
