package com.fjellsoftware.retaildemo.autogenerated.graphql.customer;

import com.fjellsoftware.javafunctionalutils.opt.Opt;

import com.fjellsoftware.javafunctionalutils.ImmutableList;

/////////////////////
/// AUTOGENERATED ///
/////////////////////

public record CustomerMutationRequest(Opt<String> operationName, ImmutableList<CustomerMutationRootField> rootFields) implements CustomerRequest {}