package com.fjellsoftware.retaildemo.autogenerated.graphql.customer;

import io.loppi.graphql.GraphQLIntrospectionQueryField;
import io.loppi.graphql.document.GraphQLOutputField;
import org.jetbrains.annotations.NotNull;

/////////////////////
/// AUTOGENERATED ///
/////////////////////

public final class CustomerIntrospectionRootField extends GraphQLIntrospectionQueryField
         implements CustomerQueryRootField{
    public CustomerIntrospectionRootField(@NotNull GraphQLOutputField rawField, int outputFieldDepth){
        super(rawField, outputFieldDepth);
    }
}