package com.fjellsoftware.retaildemo.autogenerated.graphql.customer;

/////////////////////
/// AUTOGENERATED ///
/////////////////////

public sealed interface CustomerTableMutationRootField extends CustomerMutationRootField permits 
        PlaceOrderMutationField {}