package com.fjellsoftware.retaildemo.autogenerated.graphql.customer;

import io.loppi.graphql.integration.orm.table.query.GraphQLTableQueryField;
import io.loppi.graphql.GraphQLExecutableQueryField;
import org.jetbrains.annotations.NotNull;


/////////////////////
/// AUTOGENERATED ///
/////////////////////


public sealed interface CustomerTableQueryRootField extends CustomerQueryRootField
         permits TryCurrentUserQueryField, ProductsQueryField, OrdersQueryField {}
