package com.fjellsoftware.retaildemo.autogenerated.graphql.customer;

import org.jetbrains.annotations.NotNull;
import com.fjellsoftware.javafunctionalutils.NullUtils;
import io.loppi.graphql.document.GraphQLOutputField;

/////////////////////
/// AUTOGENERATED ///
/////////////////////

public record DemoUpgradeToStaffMutationField(
        @NotNull GraphQLOutputField rawField,
        @NotNull DemoUpgradeToStaffMutationInput input)
        implements CustomerOrdinaryMutationRootField<IgnoredResult> {
    public DemoUpgradeToStaffMutationField {
        NullUtils.requireAllNonNull(rawField, input);
    }
}