package com.fjellsoftware.retaildemo.autogenerated.graphql.customer;

import com.fjellsoftware.javafunctionalutils.NullUtils;
import org.jetbrains.annotations.NotNull;
import com.fjellsoftware.javafunctionalutils.ImmutableList;
import com.fjellsoftware.javafunctionalutils.opt.Opt;
import java.util.UUID;
import java.time.OffsetDateTime;

/////////////////////
/// AUTOGENERATED ///
/////////////////////

public record DemoUpgradeToStaffMutationInput(
        ) {

}