package com.fjellsoftware.retaildemo.autogenerated.graphql.customer;

import org.jetbrains.annotations.NotNull;
import com.fjellsoftware.javafunctionalutils.NullUtils;
import io.loppi.graphql.document.GraphQLOutputField;

/////////////////////
/// AUTOGENERATED ///
/////////////////////

public record GetBcryptSaltMutationField(
        @NotNull GraphQLOutputField rawField,
        @NotNull GetBcryptSaltMutationInput input)
        implements CustomerOrdinaryMutationRootField<SaltResult> {
    public GetBcryptSaltMutationField {
        NullUtils.requireAllNonNull(rawField, input);
    }
}