package com.fjellsoftware.retaildemo.autogenerated.graphql.customer;

import org.jetbrains.annotations.NotNull;
import com.fjellsoftware.javafunctionalutils.NullUtils;
import io.loppi.graphql.document.GraphQLOutputField;

/////////////////////
/// AUTOGENERATED ///
/////////////////////

public record LoginMutationField(
        @NotNull GraphQLOutputField rawField,
        @NotNull LoginMutationInput input)
        implements CustomerOrdinaryMutationRootField<LoginResult> {
    public LoginMutationField {
        NullUtils.requireAllNonNull(rawField, input);
    }
}