package com.fjellsoftware.retaildemo.autogenerated.graphql.customer;

import io.loppi.graphql.integration.orm.table.mutation.GraphQLTableMutationField;
import com.fjellsoftware.retaildemo.autogenerated.orm.main.RetailDemoRowToMutate;
import io.loppi.graphql.integration.orm.table.query.GraphQLTableQueryFieldNoArguments;
import com.fjellsoftware.retaildemo.autogenerated.orm.main.PurchaseOrderResult;

import org.jetbrains.annotations.NotNull;
import com.fjellsoftware.javafunctionalutils.NullUtils;

/////////////////////
/// AUTOGENERATED ///
/////////////////////

public record PlaceOrderMutationField(
        @NotNull GraphQLTableQueryFieldNoArguments<PurchaseOrderResult> queryField,
        @NotNull OrderInsertMutationInput input)
        implements CustomerTableMutationRootField, GraphQLTableMutationField<PurchaseOrderResult>
{

    public PlaceOrderMutationField {
        NullUtils.requireAllNonNull(queryField, input);
    }

    @Override
    public @NotNull Iterable<RetailDemoRowToMutate> allRowsToMutate() {
        return input;
    }
}