package com.fjellsoftware.retaildemo.autogenerated.graphql.customer;
import org.jetbrains.annotations.NotNull;

import io.loppi.graphql.integration.orm.table.query.GraphQLTableQueryFieldORExpressionArguments;

import com.fjellsoftware.retaildemo.autogenerated.orm.main.ProductResult;

/////////////////////
/// AUTOGENERATED ///
/////////////////////


public final class ProductsQueryField
        extends GraphQLTableQueryFieldORExpressionArguments<ProductResult>
        implements CustomerTableQueryRootField {

    public ProductsQueryField(@NotNull GraphQLTableQueryFieldORExpressionArguments<ProductResult> queryField){
        super(queryField);
    }
}