package com.fjellsoftware.retaildemo.autogenerated.graphql.customer;

import org.jetbrains.annotations.NotNull;
import com.fjellsoftware.javafunctionalutils.NullUtils;
import com.fjellsoftware.javafunctionalutils.ImmutableList;
import com.fjellsoftware.javafunctionalutils.opt.Opt;
import java.util.UUID;
import java.time.OffsetDateTime;

/////////////////////
/// AUTOGENERATED ///
/////////////////////

public record SaltResult(
        @NotNull String salt) {
    public SaltResult {
        NullUtils.requireAllNonNull(salt);
    }
}