package com.fjellsoftware.retaildemo.autogenerated.graphql.customer;

import org.jetbrains.annotations.NotNull;
import com.fjellsoftware.javafunctionalutils.NullUtils;
import io.loppi.graphql.document.GraphQLOutputField;

/////////////////////
/// AUTOGENERATED ///
/////////////////////

public record SignUpMutationField(
        @NotNull GraphQLOutputField rawField,
        @NotNull SignUpMutationInput input)
        implements CustomerOrdinaryMutationRootField<SignUpResult> {
    public SignUpMutationField {
        NullUtils.requireAllNonNull(rawField, input);
    }
}