package com.fjellsoftware.retaildemo.autogenerated.graphql.customer;
import org.jetbrains.annotations.NotNull;

import io.loppi.graphql.integration.orm.table.query.GraphQLTableQueryFieldSimpleArguments;

import com.fjellsoftware.retaildemo.autogenerated.orm.main.UserAccountResult;

/////////////////////
/// AUTOGENERATED ///
/////////////////////


public final class TryCurrentUserQueryField
        extends GraphQLTableQueryFieldSimpleArguments<UserAccountResult>
        implements CustomerTableQueryRootField {

    public TryCurrentUserQueryField(@NotNull GraphQLTableQueryFieldSimpleArguments<UserAccountResult> queryField){
        super(queryField);
    }
}