package com.fjellsoftware.retaildemo.autogenerated.graphql.customer;

import org.jetbrains.annotations.NotNull;
import com.fjellsoftware.javafunctionalutils.NullUtils;
import io.loppi.graphql.document.GraphQLOutputField;

/////////////////////
/// AUTOGENERATED ///
/////////////////////

public record UpdatePasswordMutationField(
        @NotNull GraphQLOutputField rawField,
        @NotNull UpdatePasswordMutationInput input)
        implements CustomerOrdinaryMutationRootField<IgnoredResult> {
    public UpdatePasswordMutationField {
        NullUtils.requireAllNonNull(rawField, input);
    }
}