/*
 * © 2023. This work is openly licensed via CC0 1.0.
 * https://creativecommons.org/publicdomain/zero/1.0/
 */

package com.fjellsoftware.retaildemo.autogenerated.graphql.staff;

import com.fjellsoftware.javafunctionalutils.ImmutableList;
import io.loppi.graphql.GraphQLDatabaseMutationField;
import io.loppi.orm.metamodel.RowToMutate;
import io.loppi.graphql.GraphQLDatabaseQueryFieldNoArguments;
import com.fjellsoftware.retaildemo.autogenerated.orm.PurchaseOrderResult;
import com.fjellsoftware.retaildemo.autogenerated.orm.PurchaseOrderToDelete;
import com.fjellsoftware.retaildemo.autogenerated.orm.PurchaseOrderToInsert;
import com.fjellsoftware.retaildemo.autogenerated.orm.PurchaseOrderToUpdate;
import org.jetbrains.annotations.NotNull;
import java.util.ArrayList;
import java.util.List;

/////////////////////
/// AUTOGENERATED ///
/////////////////////

public record OrderStatusBatchUpdateMutationField(
        GraphQLDatabaseQueryFieldNoArguments<PurchaseOrderResult> queryField,
        ImmutableList<PurchaseOrderToUpdate> purchaseOrdersToUpdate
) implements StaffDatabaseMutationRootField, GraphQLDatabaseMutationField<PurchaseOrderResult> {

    @Override
    public @NotNull Iterable<RowToMutate> allRowsToMutate() {
        List<RowToMutate> rowsToMutate = new ArrayList<>();
        for (var rowToMutate : purchaseOrdersToUpdate) {
            rowsToMutate.add(rowToMutate);
        }
        return rowsToMutate;
    }
}
