package com.fjellsoftware.retaildemo.autogenerated.graphql.staff;
import org.jetbrains.annotations.NotNull;
import com.fjellsoftware.javafunctionalutils.NullUtils;

import io.loppi.graphql.integration.orm.table.query.GraphQLTableQueryFieldSimpleArguments;

import com.fjellsoftware.retaildemo.autogenerated.orm.PurchaseOrderResult;

/////////////////////
/// AUTOGENERATED ///
/////////////////////


public final class OrdersQueryField
        extends GraphQLTableQueryFieldSimpleArguments<PurchaseOrderResult>
        implements StaffTableQueryRootField {

    public OrdersQueryField(@NotNull GraphQLTableQueryFieldSimpleArguments<PurchaseOrderResult> queryField){
        super(queryField);
    }
}