/*
 * © 2023. This work is openly licensed via CC0 1.0.
 * https://creativecommons.org/publicdomain/zero/1.0/
 */

package com.fjellsoftware.retaildemo.autogenerated.graphql.staff;

import io.loppi.graphql.GraphQLDatabaseQueryFieldSimpleArguments;

import com.fjellsoftware.retaildemo.autogenerated.orm.PurchaseOrderResult;

/////////////////////
/// AUTOGENERATED ///
/////////////////////


public record OrdersQueryField(
        GraphQLDatabaseQueryFieldSimpleArguments<PurchaseOrderResult> queryField) implements StaffDatabaseQueryRootField {}
