package com.fjellsoftware.retaildemo.autogenerated.graphql.staff;

import com.fjellsoftware.javafunctionalutils.ImmutableList;
import io.loppi.graphql.integration.orm.table.mutation.GraphQLTableMutationField;
import com.fjellsoftware.retaildemo.autogenerated.orm.RetailDemoRowToMutate;
import io.loppi.graphql.integration.orm.table.query.GraphQLTableQueryFieldNoArguments;
import com.fjellsoftware.retaildemo.autogenerated.orm.ProductResult;

import org.jetbrains.annotations.NotNull;
import com.fjellsoftware.javafunctionalutils.NullUtils;
import java.util.List;
import com.fjellsoftware.retaildemo.autogenerated.graphql.staff.*;

import com.fjellsoftware.retaildemo.autogenerated.orm.ProductToInsert;

/////////////////////
/// AUTOGENERATED ///
/////////////////////

public record ProductInsertMutationField(
        @NotNull GraphQLTableQueryFieldNoArguments<ProductResult> queryField,
        @NotNull ProductToInsert input)
        implements StaffTableMutationRootField, GraphQLTableMutationField<ProductResult>
{

    public ProductInsertMutationField {
        NullUtils.requireAllNonNull(queryField, input);
    }

    @Override
    public @NotNull Iterable<RetailDemoRowToMutate> allRowsToMutate() {
        return List.of(input);
    }
}