package com.fjellsoftware.retaildemo.autogenerated.graphql.staff;

import io.loppi.graphql.integration.orm.table.mutation.GraphQLTableMutationField;
import com.fjellsoftware.retaildemo.autogenerated.orm.main.RetailDemoRowToMutate;
import io.loppi.graphql.integration.orm.table.query.GraphQLTableQueryFieldNoArguments;
import com.fjellsoftware.retaildemo.autogenerated.orm.main.ProductResult;

import org.jetbrains.annotations.NotNull;
import com.fjellsoftware.javafunctionalutils.NullUtils;
import java.util.List;

import com.fjellsoftware.retaildemo.autogenerated.orm.main.ProductToUpdate;

/////////////////////
/// AUTOGENERATED ///
/////////////////////

public record ProductUpdateMutationField(
        @NotNull GraphQLTableQueryFieldNoArguments<ProductResult> queryField,
        @NotNull ProductToUpdate input)
        implements StaffTableMutationRootField, GraphQLTableMutationField<ProductResult>
{

    public ProductUpdateMutationField {
        NullUtils.requireAllNonNull(queryField, input);
    }

    @Override
    public @NotNull Iterable<RetailDemoRowToMutate> allRowsToMutate() {
        return List.of(input);
    }
}