/*
 * © 2023. This work is openly licensed via CC0 1.0.
 * https://creativecommons.org/publicdomain/zero/1.0/
 */

package com.fjellsoftware.retaildemo.autogenerated.graphql.staff;

import com.fjellsoftware.javafunctionalutils.ImmutableList;
import io.loppi.graphql.GraphQLDatabaseMutationField;
import io.loppi.orm.metamodel.RowToMutate;
import io.loppi.graphql.GraphQLDatabaseQueryFieldNoArguments;
import com.fjellsoftware.retaildemo.autogenerated.orm.ProductResult;

import org.jetbrains.annotations.NotNull;
import java.util.List;

import com.fjellsoftware.retaildemo.autogenerated.orm.ProductToUpdate;

/////////////////////
/// AUTOGENERATED ///
/////////////////////

public record ProductUpdateMutationField(
        GraphQLDatabaseQueryFieldNoArguments<ProductResult> queryField,
        ProductToUpdate input)
        implements StaffDatabaseMutationRootField, GraphQLDatabaseMutationField<ProductResult>
{

    @Override
    public @NotNull Iterable<RowToMutate> allRowsToMutate() {
        return List.of(input);
    }
}
