/*
 * © 2023. This work is openly licensed via CC0 1.0.
 * https://creativecommons.org/publicdomain/zero/1.0/
 */

package com.fjellsoftware.retaildemo.autogenerated.graphql.staff;

import io.loppi.graphql.GraphQLQueryField;


/////////////////////
/// AUTOGENERATED ///
/////////////////////


public sealed interface StaffQueryRootField permits StaffDatabaseQueryRootField, StaffIntrospectionRootField {
    GraphQLQueryField queryField();
}
