package com.fjellsoftware.retaildemo.autogenerated.graphql.staff;

import io.loppi.graphql.integration.orm.table.query.GraphQLTableQueryField;
import io.loppi.graphql.GraphQLExecutableQueryField;
import org.jetbrains.annotations.NotNull;


/////////////////////
/// AUTOGENERATED ///
/////////////////////


public sealed interface StaffTableQueryRootField extends StaffQueryRootField
         permits OrdersQueryField, UsersQueryField, LoginSessionsQueryField {}
