package com.fjellsoftware.retaildemo.autogenerated.graphql.staff;

import com.fjellsoftware.javafunctionalutils.ImmutableList;


import com.fjellsoftware.javafunctionalutils.opt.Opt;

/////////////////////
/// AUTOGENERATED ///
/////////////////////

public record StaffQueryRequest(Opt<String> operationName, ImmutableList<StaffQueryRootField> rootFields) implements StaffRequest {}