/*
 * © 2023. This work is openly licensed via CC0 1.0.
 * https://creativecommons.org/publicdomain/zero/1.0/
 */

package com.fjellsoftware.retaildemo.autogenerated.graphql.staff;

import com.fjellsoftware.javafunctionalutils.ImmutableList;

/////////////////////
/// AUTOGENERATED ///
/////////////////////

public record StaffMutationRequest(String operationNameNullable, ImmutableList<StaffMutationRootField> rootFields) implements StaffRequest {}
