package com.fjellsoftware.retaildemo.autogenerated.graphql.staff;

import com.fjellsoftware.javafunctionalutils.opt.Opt;

import com.fjellsoftware.javafunctionalutils.ImmutableList;

/////////////////////
/// AUTOGENERATED ///
/////////////////////

public record StaffMutationRequest(Opt<String> operationName, ImmutableList<StaffMutationRootField> rootFields) implements StaffRequest {}