package com.fjellsoftware.retaildemo.autogenerated.graphql.staff;

import com.fjellsoftware.javafunctionalutils.opt.Opt;


/////////////////////
/// AUTOGENERATED ///
/////////////////////


public sealed interface StaffRequest permits StaffQueryRequest, StaffMutationRequest {
    Opt<String> operationName();
}