package com.fjellsoftware.retaildemo.autogenerated.graphql.staff;

/////////////////////
/// AUTOGENERATED ///
/////////////////////

public sealed interface StaffTableMutationRootField extends StaffMutationRootField permits 
        ProductInsertMutationField, ProductUpdateMutationField, OrderStatusBatchUpdateMutationField {}