package com.fjellsoftware.retaildemo.autogenerated.graphql.staff;

/////////////////////
/// AUTOGENERATED ///
/////////////////////

public sealed interface StaffMutationRootField permits StaffTableMutationRootField {}