package com.fjellsoftware.retaildemo.autogenerated.graphql.staff;

import io.loppi.graphql.GraphQLQueryField;


/////////////////////
/// AUTOGENERATED ///
/////////////////////


public sealed interface StaffQueryRootField permits StaffTableQueryRootField, StaffIntrospectionRootField {}
