package com.fjellsoftware.retaildemo.autogenerated.graphql.staff;
import org.jetbrains.annotations.NotNull;

import io.loppi.graphql.integration.orm.table.query.GraphQLTableQueryFieldSimpleArguments;

import com.fjellsoftware.retaildemo.autogenerated.orm.main.UserAccountResult;

/////////////////////
/// AUTOGENERATED ///
/////////////////////


public final class UsersQueryField
        extends GraphQLTableQueryFieldSimpleArguments<UserAccountResult>
        implements StaffTableQueryRootField {

    public UsersQueryField(@NotNull GraphQLTableQueryFieldSimpleArguments<UserAccountResult> queryField){
        super(queryField);
    }
}