package com.fjellsoftware.retaildemo.autogenerated.graphql.staff;
import org.jetbrains.annotations.NotNull;
import com.fjellsoftware.javafunctionalutils.NullUtils;

import io.loppi.graphql.integration.orm.table.query.GraphQLTableQueryFieldSimpleArguments;

import com.fjellsoftware.retaildemo.autogenerated.orm.UserAccountResult;

/////////////////////
/// AUTOGENERATED ///
/////////////////////


public final class UsersQueryField
        extends GraphQLTableQueryFieldSimpleArguments<UserAccountResult>
        implements StaffTableQueryRootField {

    public UsersQueryField(@NotNull GraphQLTableQueryFieldSimpleArguments<UserAccountResult> queryField){
        super(queryField);
    }
}