package com.fjellsoftware.retaildemo.autogenerated.orm.main;

import java.util.UUID;

/////////////////////
/// AUTOGENERATED ///
/////////////////////

public sealed interface LoginSessionReference extends RetailDemoRowReference permits LoginSessionToInsert, RetailDemoIdReferenceUUID {
    static LoginSessionReference of(UUID loginSessionId){
        return new RetailDemoIdReferenceUUID(loginSessionId);
    }
}
