package com.fjellsoftware.retaildemo.autogenerated.orm.main;

import io.loppi.orm.metamodel.RowToDelete;
import java.util.UUID;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

/////////////////////
/// AUTOGENERATED ///
/////////////////////

public final class LoginSessionToDelete implements RetailDemoRowToDelete, RowToDelete {
    private final UUID whereLoginSessionId;

    public LoginSessionToDelete(@NotNull UUID whereLoginSessionId){
        Objects.requireNonNull(whereLoginSessionId);
        this.whereLoginSessionId = whereLoginSessionId;
    }

    public @NotNull UUID getWhereLoginSessionId(){
        return whereLoginSessionId;
    }

}