package com.fjellsoftware.retaildemo.autogenerated.orm.main;

import io.loppi.orm.includablevalues.*;
import io.loppi.orm.metamodel.*;
import io.loppi.orm.metamodel.attribute.*;
import io.loppi.orm.metamodel.attributereference.*;
import com.fjellsoftware.javafunctionalutils.ImmutableMap;

/////////////////////
/// AUTOGENERATED ///
/////////////////////

public final class MetricKindMeta implements MetaWithIdAttribute<MetricKindResult> {
    private static final Class<MetricKindResult> referenceClass = MetricKindResult.class;

    static final String BASE_NAME = "MetricKind";
    static final String PLURAL_NAME = "MetricKinds";
    static final String TABLE_NAME = "metric_kind";

    private static final String METRIC_KIND_ID_FIELD_NAME = "metricKindId";
    private static final String NAME_FIELD_NAME = "name";
    private static final String CREATED_AT_FIELD_NAME = "createdAt";
    private static final String METRIC_VALUES_FIELD_NAME = "metricValues";

    static final ImmutableMap<String,String> COLUMN_ATTRIBUTE_NAME_TO_COLUMN_NAME = ImmutableMap.of(
            new ImmutableMap.Entry<>(METRIC_KIND_ID_FIELD_NAME, "metric_kind_id"),
            new ImmutableMap.Entry<>(NAME_FIELD_NAME, "name"),
            new ImmutableMap.Entry<>(CREATED_AT_FIELD_NAME, "created_at"));

    static final ScalarAttributeReference<MetricKindResult, IncludableLong> metricKindIdInternalReference = 
        new ScalarAttributeReference<>(referenceClass, METRIC_KIND_ID_FIELD_NAME, IncludableLong.class);
    static final PluralDerivedAssociationAttributeReference<MetricKindResult, MetricValueResult> metricValuesInternalReference = 
        new PluralDerivedAssociationAttributeReference<>(referenceClass, METRIC_VALUES_FIELD_NAME, MetricValueResult.class);

    public final ScalarAttribute<MetricKindResult, IncludableLong> metricKindId;
    public final ScalarAttribute<MetricKindResult, IncludableString> name;
    public final ScalarAttribute<MetricKindResult, IncludableOffsetDateTime> createdAt;
    public final PluralDerivedAssociationAttribute<MetricKindResult, MetricValueResult> metricValues;

    private final EntityMetadata<MetricKindResult> entity_metadata;

    @SuppressWarnings({"unchecked"})
    public MetricKindMeta(ORMMetamodel<RetailDemoTableQueryResult> oRMMetamodel){
        this.entity_metadata = oRMMetamodel.getEntityMetadata(referenceClass);
        this.metricKindId = (ScalarAttribute<MetricKindResult, IncludableLong>) entity_metadata.getScalarAttributeByName(METRIC_KIND_ID_FIELD_NAME).getOrThrow();
        this.name = (ScalarAttribute<MetricKindResult, IncludableString>) entity_metadata.getScalarAttributeByName(NAME_FIELD_NAME).getOrThrow();
        this.createdAt = (ScalarAttribute<MetricKindResult, IncludableOffsetDateTime>) entity_metadata.getScalarAttributeByName(CREATED_AT_FIELD_NAME).getOrThrow();
        this.metricValues = (PluralDerivedAssociationAttribute<MetricKindResult, MetricValueResult>) entity_metadata.getAssociationAttributeByName(METRIC_VALUES_FIELD_NAME).getOrThrow();
    }

    public EntityMetadata<MetricKindResult> getEntityMetadata(){
        return entity_metadata;
    }
}