package com.fjellsoftware.retaildemo.autogenerated.orm.main;

import java.util.UUID;

/////////////////////
/// AUTOGENERATED ///
/////////////////////

public sealed interface MetricKindReference extends RetailDemoRowReference permits MetricKindToInsert, RetailDemoIdReferenceLong {
    static MetricKindReference of(long metricKindId){
        return new RetailDemoIdReferenceLong(metricKindId);
    }
}
