package com.fjellsoftware.retaildemo.autogenerated.orm.main;

import io.loppi.orm.includablevalues.*;
import io.loppi.orm.metamodel.*;
import com.fjellsoftware.javafunctionalutils.NullUtils;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

import java.beans.ConstructorProperties;

/////////////////////
/// AUTOGENERATED ///
/////////////////////

public final class MetricValueResult implements RetailDemoTableQueryResult {
    private final IncludableLong metricValueId;
    private final IncludableAssociation<MetricKindResult> metricKind;
    private final IncludableLong metricKindId;
    private final IncludableDouble value;
    private final IncludableOffsetDateTime createdAt;

    @ConstructorProperties({"metricValueId", "metricKind", "metricKindId", "value", "createdAt"})
    public MetricValueResult(
            @NotNull IncludableLong metricValueId, @NotNull IncludableAssociation<MetricKindResult> metricKind, 
            @NotNull IncludableLong metricKindId, @NotNull IncludableDouble value, 
            @NotNull IncludableOffsetDateTime createdAt){
        NullUtils.requireAllNonNull(metricValueId, metricKind, metricKindId, value, createdAt);
        this.metricValueId = metricValueId;
        this.metricKind = metricKind;
        this.metricKindId = metricKindId;
        this.value = value;
        this.createdAt = createdAt;
    }

    public @NotNull IncludableLong getMetricValueId(){
        return metricValueId;
    }

    public @NotNull IncludableAssociation<MetricKindResult> getMetricKind(){
        return metricKind;
    }

    public @NotNull IncludableLong getMetricKindId(){
        return metricKindId;
    }

    public @NotNull IncludableDouble getValue(){
        return value;
    }

    public @NotNull IncludableOffsetDateTime getCreatedAt(){
        return createdAt;
    }


}