package com.fjellsoftware.retaildemo.autogenerated.orm.main;

import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.UUID;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

import java.beans.ConstructorProperties;
import com.fjellsoftware.javafunctionalutils.NullUtils;
import io.loppi.orm.includablevalues.*;

/////////////////////
/// AUTOGENERATED ///
/////////////////////

public final class MetricValueToInsert implements MetricValueReference, RetailDemoRowToInsert {
    private MetricKindReference metricKind;
    private double value;
    private IncludableOffsetDateTime createdAt = IncludableOffsetDateTime.notIncluded();


    @ConstructorProperties({"metricKind", "value"})
    public MetricValueToInsert(
            @NotNull MetricKindReference metricKind, @NotNull double value){
        NullUtils.requireAllNonNull(metricKind, value);
        this.metricKind = metricKind;
        this.value = value;
    }
    public @NotNull MetricKindReference getMetricKind(){
        return metricKind;
    }

    public void setMetricKind(@NotNull MetricKindReference metricKind){
        Objects.requireNonNull(metricKind);
        this.metricKind = metricKind;
    }

    public @NotNull double getValue(){
        return value;
    }

    public void setValue(@NotNull double value){
        Objects.requireNonNull(value);
        this.value = value;
    }

    public @NotNull IncludableOffsetDateTime getCreatedAt(){
        return createdAt;
    }

    public void setCreatedAt(@NotNull IncludableOffsetDateTime createdAt){
        Objects.requireNonNull(createdAt);
        this.createdAt = createdAt;
    }

    public void setCreatedAtIncludableOf(@NotNull OffsetDateTime createdAt){
        Objects.requireNonNull(createdAt);
        this.createdAt = IncludableOffsetDateTime.of(createdAt);
    }

}