package com.fjellsoftware.retaildemo.autogenerated.orm.main;

import io.loppi.orm.includablevalues.*;
import io.loppi.orm.metamodel.*;
import com.fjellsoftware.javafunctionalutils.NullUtils;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

import java.beans.ConstructorProperties;

/////////////////////
/// AUTOGENERATED ///
/////////////////////

public final class MetricKindResult implements RetailDemoTableQueryResult {
    private final IncludableLong metricKindId;
    private final IncludableString name;
    private final IncludableOffsetDateTime createdAt;
    private final IncludableAssociationList<MetricValueResult> metricValues;

    @ConstructorProperties({"metricKindId", "name", "createdAt", "metricValues"})
    public MetricKindResult(
            @NotNull IncludableLong metricKindId, @NotNull IncludableString name, 
            @NotNull IncludableOffsetDateTime createdAt, 
            @NotNull IncludableAssociationList<MetricValueResult> metricValues){
        NullUtils.requireAllNonNull(metricKindId, name, createdAt, metricValues);
        this.metricKindId = metricKindId;
        this.name = name;
        this.createdAt = createdAt;
        this.metricValues = metricValues;
    }

    public @NotNull IncludableLong getMetricKindId(){
        return metricKindId;
    }

    public @NotNull IncludableString getName(){
        return name;
    }

    public @NotNull IncludableOffsetDateTime getCreatedAt(){
        return createdAt;
    }

    public @NotNull IncludableAssociationList<MetricValueResult> getMetricValues(){
        return metricValues;
    }


}