package com.fjellsoftware.retaildemo.autogenerated.orm.main;

import java.util.UUID;

/////////////////////
/// AUTOGENERATED ///
/////////////////////

public sealed interface MetricValueReference extends RetailDemoRowReference permits MetricValueToInsert, RetailDemoIdReferenceLong {
    static MetricValueReference of(long metricValueId){
        return new RetailDemoIdReferenceLong(metricValueId);
    }
}
