package com.fjellsoftware.retaildemo.autogenerated.orm.main;

import io.loppi.orm.metamodel.RowToDelete;
import org.jetbrains.annotations.NotNull;

/////////////////////
/// AUTOGENERATED ///
/////////////////////

public final class MetricValueToDelete implements RetailDemoRowToDelete, RowToDelete {
    private final long whereMetricValueId;

    public MetricValueToDelete(long whereMetricValueId){
        this.whereMetricValueId = whereMetricValueId;
    }

    public long getWhereMetricValueId(){
        return whereMetricValueId;
    }

}