package com.fjellsoftware.retaildemo.autogenerated.orm.main;

import java.util.UUID;

/////////////////////
/// AUTOGENERATED ///
/////////////////////

public sealed interface ProductReference extends RetailDemoRowReference permits ProductToInsert, RetailDemoIdReferenceInt {
    static ProductReference of(int productId){
        return new RetailDemoIdReferenceInt(productId);
    }
}
