package com.fjellsoftware.retaildemo.autogenerated.orm.main;

import io.loppi.orm.includablevalues.*;
import io.loppi.orm.metamodel.*;
import io.loppi.orm.metamodel.attribute.*;
import io.loppi.orm.metamodel.attributereference.*;
import com.fjellsoftware.javafunctionalutils.ImmutableMap;

/////////////////////
/// AUTOGENERATED ///
/////////////////////

public final class ProductMeta implements MetaWithIdAttribute<ProductResult> {
    private static final Class<ProductResult> referenceClass = ProductResult.class;

    static final String BASE_NAME = "Product";
    static final String PLURAL_NAME = "Products";
    static final String TABLE_NAME = "product";

    private static final String PRODUCT_ID_FIELD_NAME = "productId";
    private static final String STOCK_CODE_FIELD_NAME = "stockCode";
    private static final String DESCRIPTION_FIELD_NAME = "description";
    private static final String CURRENT_UNIT_PRICE_FIELD_NAME = "currentUnitPrice";
    private static final String CREATED_AT_FIELD_NAME = "createdAt";
    private static final String LAST_UPDATED_AT_FIELD_NAME = "lastUpdatedAt";
    private static final String ORDER_LINES_FIELD_NAME = "orderLines";

    static final ImmutableMap<String,String> COLUMN_ATTRIBUTE_NAME_TO_COLUMN_NAME = ImmutableMap.of(
            new ImmutableMap.Entry<>(PRODUCT_ID_FIELD_NAME, "product_id"),
            new ImmutableMap.Entry<>(STOCK_CODE_FIELD_NAME, "stock_code"),
            new ImmutableMap.Entry<>(DESCRIPTION_FIELD_NAME, "description"),
            new ImmutableMap.Entry<>(CURRENT_UNIT_PRICE_FIELD_NAME, "current_unit_price"),
            new ImmutableMap.Entry<>(CREATED_AT_FIELD_NAME, "created_at"),
            new ImmutableMap.Entry<>(LAST_UPDATED_AT_FIELD_NAME, "last_updated_at"));

    static final ScalarAttributeReference<ProductResult, IncludableInt> productIdInternalReference = 
        new ScalarAttributeReference<>(referenceClass, PRODUCT_ID_FIELD_NAME, IncludableInt.class);
    static final PluralDerivedAssociationAttributeReference<ProductResult, OrderLineResult> orderLinesInternalReference = 
        new PluralDerivedAssociationAttributeReference<>(referenceClass, ORDER_LINES_FIELD_NAME, OrderLineResult.class);

    public final ScalarAttribute<ProductResult, IncludableInt> productId;
    public final ScalarAttribute<ProductResult, IncludableString> stockCode;
    public final ScalarAttribute<ProductResult, IncludableString> description;
    public final ScalarAttribute<ProductResult, IncludableBigDecimal> currentUnitPrice;
    public final ScalarAttribute<ProductResult, IncludableOffsetDateTime> createdAt;
    public final ScalarAttribute<ProductResult, IncludableOffsetDateTime> lastUpdatedAt;
    public final PluralDerivedAssociationAttribute<ProductResult, OrderLineResult> orderLines;

    private final EntityMetadata<ProductResult> entity_metadata;

    @SuppressWarnings({"unchecked"})
    public ProductMeta(ORMMetamodel<RetailDemoTableQueryResult> oRMMetamodel){
        this.entity_metadata = oRMMetamodel.getEntityMetadata(referenceClass);
        this.productId = (ScalarAttribute<ProductResult, IncludableInt>) entity_metadata.getScalarAttributeByName(PRODUCT_ID_FIELD_NAME).getOrThrow();
        this.stockCode = (ScalarAttribute<ProductResult, IncludableString>) entity_metadata.getScalarAttributeByName(STOCK_CODE_FIELD_NAME).getOrThrow();
        this.description = (ScalarAttribute<ProductResult, IncludableString>) entity_metadata.getScalarAttributeByName(DESCRIPTION_FIELD_NAME).getOrThrow();
        this.currentUnitPrice = (ScalarAttribute<ProductResult, IncludableBigDecimal>) entity_metadata.getScalarAttributeByName(CURRENT_UNIT_PRICE_FIELD_NAME).getOrThrow();
        this.createdAt = (ScalarAttribute<ProductResult, IncludableOffsetDateTime>) entity_metadata.getScalarAttributeByName(CREATED_AT_FIELD_NAME).getOrThrow();
        this.lastUpdatedAt = (ScalarAttribute<ProductResult, IncludableOffsetDateTime>) entity_metadata.getScalarAttributeByName(LAST_UPDATED_AT_FIELD_NAME).getOrThrow();
        this.orderLines = (PluralDerivedAssociationAttribute<ProductResult, OrderLineResult>) entity_metadata.getAssociationAttributeByName(ORDER_LINES_FIELD_NAME).getOrThrow();
    }

    public EntityMetadata<ProductResult> getEntityMetadata(){
        return entity_metadata;
    }
}