package com.fjellsoftware.retaildemo.autogenerated.orm.main;

import io.loppi.orm.includablevalues.*;
import io.loppi.orm.metamodel.*;
import io.loppi.orm.metamodel.attribute.*;
import io.loppi.orm.metamodel.attributereference.*;
import com.fjellsoftware.javafunctionalutils.ImmutableMap;

/////////////////////
/// AUTOGENERATED ///
/////////////////////

public final class PurchaseOrderMeta implements MetaWithIdAttribute<PurchaseOrderResult> {
    private static final Class<PurchaseOrderResult> referenceClass = PurchaseOrderResult.class;

    static final String BASE_NAME = "PurchaseOrder";
    static final String PLURAL_NAME = "PurchaseOrders";
    static final String TABLE_NAME = "purchase_order";

    private static final String PURCHASE_ORDER_ID_FIELD_NAME = "purchaseOrderId";
    private static final String COUNTRY_FIELD_NAME = "country";
    private static final String COUNTRY_ID_FIELD_NAME = "countryId";
    private static final String CREATED_AT_FIELD_NAME = "createdAt";
    private static final String LAST_UPDATED_AT_FIELD_NAME = "lastUpdatedAt";
    private static final String ORDER_STATUS_FIELD_NAME = "orderStatus";
    private static final String ADDRESS_FIELD_NAME = "address";
    private static final String NAME_FIELD_NAME = "name";
    private static final String PHONE_NUMBER_FIELD_NAME = "phoneNumber";
    private static final String CUSTOMER_FIELD_NAME = "customer";
    private static final String CUSTOMER_ID_FIELD_NAME = "customerId";
    private static final String ORDER_LINES_FIELD_NAME = "orderLines";

    static final ImmutableMap<String,String> COLUMN_ATTRIBUTE_NAME_TO_COLUMN_NAME = ImmutableMap.of(
            new ImmutableMap.Entry<>(PURCHASE_ORDER_ID_FIELD_NAME, "purchase_order_id"),
            new ImmutableMap.Entry<>(COUNTRY_FIELD_NAME, "country_id"),
            new ImmutableMap.Entry<>(COUNTRY_ID_FIELD_NAME, "country_id"),
            new ImmutableMap.Entry<>(CREATED_AT_FIELD_NAME, "created_at"),
            new ImmutableMap.Entry<>(LAST_UPDATED_AT_FIELD_NAME, "last_updated_at"),
            new ImmutableMap.Entry<>(ORDER_STATUS_FIELD_NAME, "order_status"),
            new ImmutableMap.Entry<>(ADDRESS_FIELD_NAME, "address"),
            new ImmutableMap.Entry<>(NAME_FIELD_NAME, "name"),
            new ImmutableMap.Entry<>(PHONE_NUMBER_FIELD_NAME, "phone_number"),
            new ImmutableMap.Entry<>(CUSTOMER_FIELD_NAME, "customer_id"),
            new ImmutableMap.Entry<>(CUSTOMER_ID_FIELD_NAME, "customer_id"));

    static final ScalarAttributeReference<PurchaseOrderResult, IncludableInt> purchaseOrderIdInternalReference = 
        new ScalarAttributeReference<>(referenceClass, PURCHASE_ORDER_ID_FIELD_NAME, IncludableInt.class);
    static final OwnerAssociationAttributeReference<PurchaseOrderResult, IncludableAssociation<CountryResult>, CountryResult> countryInternalReference = 
        new OwnerAssociationAttributeReference<>(referenceClass, COUNTRY_FIELD_NAME, false, CountryResult.class);
    static final OwnerAssociationAttributeReference<PurchaseOrderResult, IncludableNullableAssociation<UserAccountResult>, UserAccountResult> customerInternalReference = 
        new OwnerAssociationAttributeReference<>(referenceClass, CUSTOMER_FIELD_NAME, true, UserAccountResult.class);
    static final PluralDerivedAssociationAttributeReference<PurchaseOrderResult, OrderLineResult> orderLinesInternalReference = 
        new PluralDerivedAssociationAttributeReference<>(referenceClass, ORDER_LINES_FIELD_NAME, OrderLineResult.class);

    public final ScalarAttribute<PurchaseOrderResult, IncludableInt> purchaseOrderId;
    public final OwnerAssociationAttribute<PurchaseOrderResult, IncludableAssociation<CountryResult>, CountryResult> country;
    public final ScalarAttribute<PurchaseOrderResult, IncludableInt> countryId;
    public final ScalarAttribute<PurchaseOrderResult, IncludableOffsetDateTime> createdAt;
    public final ScalarAttribute<PurchaseOrderResult, IncludableOffsetDateTime> lastUpdatedAt;
    public final ScalarAttribute<PurchaseOrderResult, IncludableString> orderStatus;
    public final ScalarAttribute<PurchaseOrderResult, IncludableString> address;
    public final ScalarAttribute<PurchaseOrderResult, IncludableString> name;
    public final ScalarAttribute<PurchaseOrderResult, IncludableString> phoneNumber;
    public final OwnerAssociationAttribute<PurchaseOrderResult, IncludableNullableAssociation<UserAccountResult>, UserAccountResult> customer;
    public final ScalarAttribute<PurchaseOrderResult, IncludableNullableUUID> customerId;
    public final PluralDerivedAssociationAttribute<PurchaseOrderResult, OrderLineResult> orderLines;

    private final EntityMetadata<PurchaseOrderResult> entity_metadata;

    @SuppressWarnings({"unchecked"})
    public PurchaseOrderMeta(ORMMetamodel<RetailDemoTableQueryResult> oRMMetamodel){
        this.entity_metadata = oRMMetamodel.getEntityMetadata(referenceClass);
        this.purchaseOrderId = (ScalarAttribute<PurchaseOrderResult, IncludableInt>) entity_metadata.getScalarAttributeByName(PURCHASE_ORDER_ID_FIELD_NAME).getOrThrow();
        this.country = (OwnerAssociationAttribute<PurchaseOrderResult, IncludableAssociation<CountryResult>, CountryResult>) entity_metadata.getAssociationAttributeByName(COUNTRY_FIELD_NAME).getOrThrow();
        this.countryId = (ScalarAttribute<PurchaseOrderResult, IncludableInt>) entity_metadata.getScalarAttributeByName(COUNTRY_ID_FIELD_NAME).getOrThrow();
        this.createdAt = (ScalarAttribute<PurchaseOrderResult, IncludableOffsetDateTime>) entity_metadata.getScalarAttributeByName(CREATED_AT_FIELD_NAME).getOrThrow();
        this.lastUpdatedAt = (ScalarAttribute<PurchaseOrderResult, IncludableOffsetDateTime>) entity_metadata.getScalarAttributeByName(LAST_UPDATED_AT_FIELD_NAME).getOrThrow();
        this.orderStatus = (ScalarAttribute<PurchaseOrderResult, IncludableString>) entity_metadata.getScalarAttributeByName(ORDER_STATUS_FIELD_NAME).getOrThrow();
        this.address = (ScalarAttribute<PurchaseOrderResult, IncludableString>) entity_metadata.getScalarAttributeByName(ADDRESS_FIELD_NAME).getOrThrow();
        this.name = (ScalarAttribute<PurchaseOrderResult, IncludableString>) entity_metadata.getScalarAttributeByName(NAME_FIELD_NAME).getOrThrow();
        this.phoneNumber = (ScalarAttribute<PurchaseOrderResult, IncludableString>) entity_metadata.getScalarAttributeByName(PHONE_NUMBER_FIELD_NAME).getOrThrow();
        this.customer = (OwnerAssociationAttribute<PurchaseOrderResult, IncludableNullableAssociation<UserAccountResult>, UserAccountResult>) entity_metadata.getAssociationAttributeByName(CUSTOMER_FIELD_NAME).getOrThrow();
        this.customerId = (ScalarAttribute<PurchaseOrderResult, IncludableNullableUUID>) entity_metadata.getScalarAttributeByName(CUSTOMER_ID_FIELD_NAME).getOrThrow();
        this.orderLines = (PluralDerivedAssociationAttribute<PurchaseOrderResult, OrderLineResult>) entity_metadata.getAssociationAttributeByName(ORDER_LINES_FIELD_NAME).getOrThrow();
    }

    public EntityMetadata<PurchaseOrderResult> getEntityMetadata(){
        return entity_metadata;
    }
}