package com.fjellsoftware.retaildemo.autogenerated.orm.main;

import io.loppi.orm.metamodel.RowToDelete;
import org.jetbrains.annotations.NotNull;

/////////////////////
/// AUTOGENERATED ///
/////////////////////

public final class PurchaseOrderToDelete implements RetailDemoRowToDelete, RowToDelete {
    private final int wherePurchaseOrderId;

    public PurchaseOrderToDelete(int wherePurchaseOrderId){
        this.wherePurchaseOrderId = wherePurchaseOrderId;
    }

    public int getWherePurchaseOrderId(){
        return wherePurchaseOrderId;
    }

}