package com.fjellsoftware.retaildemo.autogenerated.orm.main;

import io.loppi.orm.metamodel.AggregateQueryResult;

/////////////////////
/// AUTOGENERATED ///
/////////////////////

public interface RetailDemoAggregateQueryResult extends AggregateQueryResult {
}