package com.fjellsoftware.retaildemo.autogenerated.orm.main;

import io.loppi.orm.metamodel.SQLRoutineResult;

/////////////////////
/// AUTOGENERATED ///
/////////////////////

public interface RetailDemoSQLRoutineResult extends SQLRoutineResult {
}