package com.fjellsoftware.retaildemo.autogenerated.orm.main;

import io.loppi.orm.metamodel.RowReference;

/////////////////////
/// AUTOGENERATED ///
/////////////////////

public sealed interface RetailDemoRowReference extends RowReference permits 
CountryReference, LoginSessionReference, MetricKindReference, MetricValueReference, OrderLineReference, 
ProductReference, PurchaseOrderReference, UserAccountReference {
}