package com.fjellsoftware.retaildemo.autogenerated.orm.main;

import io.loppi.orm.metamodel.RowToUpdate;

/////////////////////
/// AUTOGENERATED ///
/////////////////////

public sealed interface RetailDemoRowToUpdate extends RowToUpdate, RetailDemoRowToUpsert permits 
CountryToUpdate, LoginSessionToUpdate, MetricKindToUpdate, MetricValueToUpdate, OrderLineToUpdate, 
ProductToUpdate, PurchaseOrderToUpdate, UserAccountToUpdate {}