package com.fjellsoftware.retaildemo.autogenerated.orm.main;

import io.loppi.orm.metamodel.ORMMetamodel;
import io.loppi.orm.metamodel.sql.DatabaseSchema;
import org.jetbrains.annotations.NotNull;

/////////////////////
/// AUTOGENERATED ///
/////////////////////

public final class RetailDemoMeta{
    private final ORMMetamodel<RetailDemoTableQueryResult> oRMMetamodel;
    private final DatabaseSchema databaseSchema;
    private final CountryMeta countryMeta;
    private final LoginSessionMeta loginSessionMeta;
    private final OrderLineMeta orderLineMeta;
    private final ProductMeta productMeta;
    private final PurchaseOrderMeta purchaseOrderMeta;
    private final UserAccountMeta userAccountMeta;

    RetailDemoMeta(ORMMetamodel<RetailDemoTableQueryResult> oRMMetamodel, DatabaseSchema databaseSchema){
        this.oRMMetamodel = oRMMetamodel;
        this.databaseSchema = databaseSchema;
        this.countryMeta = new CountryMeta(oRMMetamodel);
        this.loginSessionMeta = new LoginSessionMeta(oRMMetamodel);
        this.orderLineMeta = new OrderLineMeta(oRMMetamodel);
        this.productMeta = new ProductMeta(oRMMetamodel);
        this.purchaseOrderMeta = new PurchaseOrderMeta(oRMMetamodel);
        this.userAccountMeta = new UserAccountMeta(oRMMetamodel);
    }

    public @NotNull ORMMetamodel<RetailDemoTableQueryResult> getORMMetamodel(){
        return oRMMetamodel;
    }

    public @NotNull DatabaseSchema getSchema(){
        return databaseSchema;
    }

    public @NotNull CountryMeta getCountryMeta(){
        return countryMeta;
    }

    public @NotNull LoginSessionMeta getLoginSessionMeta(){
        return loginSessionMeta;
    }

    public @NotNull OrderLineMeta getOrderLineMeta(){
        return orderLineMeta;
    }

    public @NotNull ProductMeta getProductMeta(){
        return productMeta;
    }

    public @NotNull PurchaseOrderMeta getPurchaseOrderMeta(){
        return purchaseOrderMeta;
    }

    public @NotNull UserAccountMeta getUserAccountMeta(){
        return userAccountMeta;
    }

}