package com.fjellsoftware.retaildemo.autogenerated.orm.main;

import io.loppi.orm.metamodel.RowToDelete;

/////////////////////
/// AUTOGENERATED ///
/////////////////////

public sealed interface RetailDemoRowToDelete extends RowToDelete, RetailDemoRowToMutate permits 
CountryToDelete, LoginSessionToDelete, MetricKindToDelete, MetricValueToDelete, OrderLineToDelete, 
ProductToDelete, PurchaseOrderToDelete, UserAccountToDelete {}