package com.fjellsoftware.retaildemo.autogenerated.orm.main;

import io.loppi.orm.metamodel.*;
import java.util.Arrays;
import java.util.List;

/////////////////////
/// AUTOGENERATED ///
/////////////////////

public final class RetailDemoMetaConfiguration{
    public List<EntityMetadataConfiguration<? extends TableQueryResult>> createEveryMetadataConfiguration(){
        return Arrays.asList(
            createCountryResultMetadata(),
            createLoginSessionResultMetadata(),
            createOrderLineResultMetadata(),
            createProductResultMetadata(),
            createPurchaseOrderResultMetadata(),
            createUserAccountResultMetadata());
    }

    private EntityMetadataConfiguration<CountryResult> createCountryResultMetadata() {
        return new EntityMetadataConfiguration<>(
                CountryMeta.BASE_NAME, CountryMeta.PLURAL_NAME,
                CountryMeta.TABLE_NAME, CountryMeta.COLUMN_ATTRIBUTE_NAME_TO_COLUMN_NAME,
                CountryResult.class, CountryToInsert.class)
                .setIdUpdateDeleteReference(CountryMeta.countryIdInternalReference,
                        CountryToUpdate.class, CountryToDelete.class, CountryReference.class)
                .mapPluralAttributeToSingularAttribute(CountryMeta.purchaseOrdersInternalReference, PurchaseOrderMeta.countryInternalReference);
    }

    private EntityMetadataConfiguration<LoginSessionResult> createLoginSessionResultMetadata() {
        return new EntityMetadataConfiguration<>(
                LoginSessionMeta.BASE_NAME, LoginSessionMeta.PLURAL_NAME,
                LoginSessionMeta.TABLE_NAME, LoginSessionMeta.COLUMN_ATTRIBUTE_NAME_TO_COLUMN_NAME,
                LoginSessionResult.class, LoginSessionToInsert.class)
                .setIdUpdateDeleteReference(LoginSessionMeta.loginSessionIdInternalReference,
                        LoginSessionToUpdate.class, LoginSessionToDelete.class, LoginSessionReference.class);
    }

    private EntityMetadataConfiguration<OrderLineResult> createOrderLineResultMetadata() {
        return new EntityMetadataConfiguration<>(
                OrderLineMeta.BASE_NAME, OrderLineMeta.PLURAL_NAME,
                OrderLineMeta.TABLE_NAME, OrderLineMeta.COLUMN_ATTRIBUTE_NAME_TO_COLUMN_NAME,
                OrderLineResult.class, OrderLineToInsert.class)
                .setIdUpdateDeleteReference(OrderLineMeta.orderLineIdInternalReference,
                        OrderLineToUpdate.class, OrderLineToDelete.class, OrderLineReference.class);
    }

    private EntityMetadataConfiguration<ProductResult> createProductResultMetadata() {
        return new EntityMetadataConfiguration<>(
                ProductMeta.BASE_NAME, ProductMeta.PLURAL_NAME,
                ProductMeta.TABLE_NAME, ProductMeta.COLUMN_ATTRIBUTE_NAME_TO_COLUMN_NAME,
                ProductResult.class, ProductToInsert.class)
                .setIdUpdateDeleteReference(ProductMeta.productIdInternalReference,
                        ProductToUpdate.class, ProductToDelete.class, ProductReference.class)
                .mapPluralAttributeToSingularAttribute(ProductMeta.orderLinesInternalReference, OrderLineMeta.productInternalReference);
    }

    private EntityMetadataConfiguration<PurchaseOrderResult> createPurchaseOrderResultMetadata() {
        return new EntityMetadataConfiguration<>(
                PurchaseOrderMeta.BASE_NAME, PurchaseOrderMeta.PLURAL_NAME,
                PurchaseOrderMeta.TABLE_NAME, PurchaseOrderMeta.COLUMN_ATTRIBUTE_NAME_TO_COLUMN_NAME,
                PurchaseOrderResult.class, PurchaseOrderToInsert.class)
                .setIdUpdateDeleteReference(PurchaseOrderMeta.purchaseOrderIdInternalReference,
                        PurchaseOrderToUpdate.class, PurchaseOrderToDelete.class, PurchaseOrderReference.class)
                .mapPluralAttributeToSingularAttribute(PurchaseOrderMeta.orderLinesInternalReference, OrderLineMeta.purchaseOrderInternalReference);
    }

    private EntityMetadataConfiguration<UserAccountResult> createUserAccountResultMetadata() {
        return new EntityMetadataConfiguration<>(
                UserAccountMeta.BASE_NAME, UserAccountMeta.PLURAL_NAME,
                UserAccountMeta.TABLE_NAME, UserAccountMeta.COLUMN_ATTRIBUTE_NAME_TO_COLUMN_NAME,
                UserAccountResult.class, UserAccountToInsert.class)
                .setIdUpdateDeleteReference(UserAccountMeta.userAccountIdInternalReference,
                        UserAccountToUpdate.class, UserAccountToDelete.class, UserAccountReference.class)
                .mapPluralAttributeToSingularAttribute(UserAccountMeta.loginSessionsInternalReference, LoginSessionMeta.userAccountInternalReference)
                .mapPluralAttributeToSingularAttribute(UserAccountMeta.purchaseOrdersInternalReference, PurchaseOrderMeta.customerInternalReference);
    }
}