package com.fjellsoftware.retaildemo.autogenerated.orm.main;

import io.loppi.orm.metamodel.ViewQueryResult;

/////////////////////
/// AUTOGENERATED ///
/////////////////////

public interface RetailDemoViewQueryResult extends ViewQueryResult {
}