package com.fjellsoftware.retaildemo.autogenerated.orm.main;

import io.loppi.orm.metamodel.RowToUpdate;

/////////////////////
/// AUTOGENERATED ///
/////////////////////

public sealed interface RetailDemoRowToUpdate extends RowToUpdate, RetailDemoRowToUpsert permits 
CountryToUpdate, LoginSessionToUpdate, OrderLineToUpdate, ProductToUpdate, PurchaseOrderToUpdate, 
UserAccountToUpdate {}