package com.fjellsoftware.retaildemo.autogenerated.orm.main;

import java.util.UUID;

/////////////////////
/// AUTOGENERATED ///
/////////////////////

public sealed interface UserAccountReference extends RetailDemoRowReference permits UserAccountToInsert, RetailDemoIdReferenceUUID {
    static UserAccountReference of(UUID userAccountId){
        return new RetailDemoIdReferenceUUID(userAccountId);
    }
}
