package com.fjellsoftware.retaildemo.autogenerated.orm.main;

import io.loppi.orm.includablevalues.*;
import io.loppi.orm.metamodel.*;
import com.fjellsoftware.javafunctionalutils.NullUtils;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

import java.beans.ConstructorProperties;

/////////////////////
/// AUTOGENERATED ///
/////////////////////

public final class UserAccountResult implements RetailDemoTableQueryResult {
    private final IncludableString name;
    private final IncludableString username;
    private final IncludableString hashedPassword;
    private final IncludableOffsetDateTime createdAt;
    private final IncludableOffsetDateTime lastUpdatedAt;
    private final IncludableString role;
    private final IncludableUUID userAccountId;
    private final IncludableAssociationList<LoginSessionResult> loginSessions;
    private final IncludableAssociationList<PurchaseOrderResult> purchaseOrders;

    @ConstructorProperties({"name", "username", "hashedPassword", "createdAt", "lastUpdatedAt", "role", 
        "userAccountId", "loginSessions", "purchaseOrders"})
    public UserAccountResult(
            @NotNull IncludableString name, @NotNull IncludableString username, 
            @NotNull IncludableString hashedPassword, @NotNull IncludableOffsetDateTime createdAt, 
            @NotNull IncludableOffsetDateTime lastUpdatedAt, @NotNull IncludableString role, 
            @NotNull IncludableUUID userAccountId, 
            @NotNull IncludableAssociationList<LoginSessionResult> loginSessions, 
            @NotNull IncludableAssociationList<PurchaseOrderResult> purchaseOrders){
        NullUtils.requireAllNonNull(name, username, hashedPassword, createdAt, lastUpdatedAt, role, userAccountId, 
                loginSessions, purchaseOrders);
        this.name = name;
        this.username = username;
        this.hashedPassword = hashedPassword;
        this.createdAt = createdAt;
        this.lastUpdatedAt = lastUpdatedAt;
        this.role = role;
        this.userAccountId = userAccountId;
        this.loginSessions = loginSessions;
        this.purchaseOrders = purchaseOrders;
    }

    public @NotNull IncludableString getName(){
        return name;
    }

    public @NotNull IncludableString getUsername(){
        return username;
    }

    public @NotNull IncludableString getHashedPassword(){
        return hashedPassword;
    }

    public @NotNull IncludableOffsetDateTime getCreatedAt(){
        return createdAt;
    }

    public @NotNull IncludableOffsetDateTime getLastUpdatedAt(){
        return lastUpdatedAt;
    }

    public @NotNull IncludableString getRole(){
        return role;
    }

    public @NotNull IncludableUUID getUserAccountId(){
        return userAccountId;
    }

    public @NotNull IncludableAssociationList<LoginSessionResult> getLoginSessions(){
        return loginSessions;
    }

    public @NotNull IncludableAssociationList<PurchaseOrderResult> getPurchaseOrders(){
        return purchaseOrders;
    }


}