package com.fjellsoftware.retaildemo.autogenerated.orm.main;

import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.UUID;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

import java.beans.ConstructorProperties;
import com.fjellsoftware.javafunctionalutils.NullUtils;
import io.loppi.orm.includablevalues.*;

/////////////////////
/// AUTOGENERATED ///
/////////////////////

public final class UserAccountToInsert implements UserAccountReference, RetailDemoRowToInsert {
    private String name;
    private String username;
    private String hashedPassword;
    private IncludableOffsetDateTime createdAt = IncludableOffsetDateTime.notIncluded();
    private IncludableOffsetDateTime lastUpdatedAt = IncludableOffsetDateTime.notIncluded();
    private IncludableString role = IncludableString.notIncluded();
    private IncludableUUID userAccountId = IncludableUUID.notIncluded();


    @ConstructorProperties({"name", "username", "hashedPassword"})
    public UserAccountToInsert(
            @NotNull String name, @NotNull String username, @NotNull String hashedPassword){
        NullUtils.requireAllNonNull(hashedPassword, name, username);
        this.name = name;
        this.username = username;
        this.hashedPassword = hashedPassword;
    }
    public @NotNull String getName(){
        return name;
    }

    public void setName(@NotNull String name){
        Objects.requireNonNull(name);
        this.name = name;
    }

    public @NotNull String getUsername(){
        return username;
    }

    public void setUsername(@NotNull String username){
        Objects.requireNonNull(username);
        this.username = username;
    }

    public @NotNull String getHashedPassword(){
        return hashedPassword;
    }

    public void setHashedPassword(@NotNull String hashedPassword){
        Objects.requireNonNull(hashedPassword);
        this.hashedPassword = hashedPassword;
    }

    public @NotNull IncludableOffsetDateTime getCreatedAt(){
        return createdAt;
    }

    public void setCreatedAt(@NotNull IncludableOffsetDateTime createdAt){
        Objects.requireNonNull(createdAt);
        this.createdAt = createdAt;
    }

    public void setCreatedAtIncludableOf(@NotNull OffsetDateTime createdAt){
        Objects.requireNonNull(createdAt);
        this.createdAt = IncludableOffsetDateTime.of(createdAt);
    }

    public @NotNull IncludableOffsetDateTime getLastUpdatedAt(){
        return lastUpdatedAt;
    }

    public void setLastUpdatedAt(@NotNull IncludableOffsetDateTime lastUpdatedAt){
        Objects.requireNonNull(lastUpdatedAt);
        this.lastUpdatedAt = lastUpdatedAt;
    }

    public void setLastUpdatedAtIncludableOf(@NotNull OffsetDateTime lastUpdatedAt){
        Objects.requireNonNull(lastUpdatedAt);
        this.lastUpdatedAt = IncludableOffsetDateTime.of(lastUpdatedAt);
    }

    public @NotNull IncludableString getRole(){
        return role;
    }

    public void setRole(@NotNull IncludableString role){
        Objects.requireNonNull(role);
        this.role = role;
    }

    public void setRoleIncludableOf(@NotNull String role){
        Objects.requireNonNull(role);
        this.role = IncludableString.of(role);
    }

    public @NotNull IncludableUUID getUserAccountId(){
        return userAccountId;
    }

    public void setUserAccountId(@NotNull IncludableUUID userAccountId){
        Objects.requireNonNull(userAccountId);
        this.userAccountId = userAccountId;
    }

    public void setUserAccountIdIncludableOf(@NotNull UUID userAccountId){
        Objects.requireNonNull(userAccountId);
        this.userAccountId = IncludableUUID.of(userAccountId);
    }

}