/*
 * © 2023. This work is openly licensed via CC0 1.0.
 * https://creativecommons.org/publicdomain/zero/1.0/
 */

package com.fjellsoftware.retaildemo.development;

import com.fjellsoftware.retaildemo.ApplicationConfiguration;
import com.fjellsoftware.retaildemo.CoreDependencies;
import com.fjellsoftware.retaildemo.LoggerInitializer;
import io.loppi.graphql.GraphQLService;
import io.loppi.graphql.LoppiGraphQLClassGenerator;
import com.fjellsoftware.retaildemo.util.FileUtils;

import java.io.File;
import java.nio.file.Path;

public class GraphQLClassGenerator {

    public static void main(String[] args) {
        LoggerInitializer.initializeDevelopmentConsoleLogger();
        new GraphQLClassGenerator().generateClasses();
    }
    public void generateClasses(){
        Path autogeneratedGraphQLRootPath = Path.of(ORMClassGenerator.autogeneratedDirectoryPath.toString(),"graphql");
        File directory = autogeneratedGraphQLRootPath.toFile();
        FileUtils.purgeDirectory(directory);

        CoreDependencies coreDependencies = new CoreDependencies(new ApplicationConfiguration());
        String packageNameBase = "com.fjellsoftware.retaildemo.autogenerated.graphql";

        String customerPrefix = "Customer";
        String customerLowerCase = "customer";
        String customerPackageName = packageNameBase + "." + customerLowerCase;
        Path customerPath = Path.of(autogeneratedGraphQLRootPath.toString(), customerLowerCase);
        GraphQLService customerGraphQLService = coreDependencies.getCustomerGraphQLServiceRaw();
        LoppiGraphQLClassGenerator.generateGraphQLClassFilesFromSchema(customerGraphQLService,
                customerPath, customerPrefix,customerPackageName);

        String staffPrefix = "Staff";
        String staffLowerCase = "staff";
        Path staffPath = Path.of(autogeneratedGraphQLRootPath.toString(), staffLowerCase);
        String staffPackageName = packageNameBase+ "." + staffLowerCase;
        GraphQLService staffGraphQLService = coreDependencies.getStaffGraphQLServiceRaw();
        LoppiGraphQLClassGenerator.generateGraphQLClassFilesFromSchema(staffGraphQLService,
                staffPath, staffPrefix,staffPackageName);
    }
}
