/*
 * © 2023. This work is openly licensed via CC0 1.0.
 * https://creativecommons.org/publicdomain/zero/1.0/
 */

package com.fjellsoftware.retaildemo.development;

import com.fjellsoftware.retaildemo.CoreDependencies;
import com.fjellsoftware.retaildemo.LoggerInitializer;
import io.loppi.orm.metamodel.LoppiClassGenerator;
import io.loppi.orm.metamodel.LoppiClassGeneratorConfiguration;
import com.fjellsoftware.retaildemo.util.FileUtils;

import java.io.File;
import java.nio.file.Path;

public class ORMClassGenerator {

    public static void main(String[] args) {
        LoggerInitializer.initializeDevelopmentConsoleLogger();
        new ORMClassGenerator().generateClasses();
    }

    public static final String PROJECT_ROOT_PATH = System.getProperty("user.dir");
    public static final Path autogeneratedDirectoryPath = Path.of(PROJECT_ROOT_PATH, "src", "main", "java", "com",
            "fjellsoftware", "retaildemo", "autogenerated");
    public void generateClasses(){
        Path ormPath = Path.of(autogeneratedDirectoryPath.toString(), "orm");
        File directory = ormPath.toFile();
        FileUtils.purgeDirectory(directory);
        LoppiClassGeneratorConfiguration generatorConfiguration = new LoppiClassGeneratorConfiguration(
                CoreDependencies.createDataSource(System.getProperty("user.home")), ormPath,
                "com.fjellsoftware.retaildemo.autogenerated.orm");
        LoppiClassGenerator.generateLoppiClassFiles(generatorConfiguration);
    }
}
